### ISSUE TITLE
[Prioridade Baixa] Menu Principal nao esta no mesmo formato

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#103]
Pessoal, a cliente esta requisitando que o Menu tenha a mesma aparencia do layout:

Como esta:
![image](https://cloud.githubusercontent.com/assets/5949986/11788405/7de670c8-a256-11e5-86e3-44dc2420a2ca.png)

Apontamento da cliente:

![image](https://cloud.githubusercontent.com/assets/5949986/11788397/71244bb2-a256-11e5-8302-40de3fcbcdae.png)

Verifique na pasta do projeto o layout original.

**Comment by matheusgimenez** [comment]
No BrasaWP

**Comment by LuwkasLima** [comment]
@isaquebrasileiro ficou bem proximo, mas vamos da ruma refinada rapida (sei que foi dificil pra vc, ja que nao tinhamos o PSD, entao vou te ajudar...)

1 - Tenta subir o Titulo dos botoes mais pro meio (deixando a mesma distancia de cima e de baixo):

![image](https://cloud.githubusercontent.com/assets/5949986/14333096/9862dd36-fc12-11e5-9218-d21b178c0063.png)

2 - Tenta deixar a fonte um pouco maior em alguns pixels como no layout:

![image](https://cloud.githubusercontent.com/assets/5949986/14333184/01f23800-fc13-11e5-914a-3704ee315f03.png)

3 - Consegue deixar alinhado o terceiro nivel do menu com o segundo nivel?

![image](https://cloud.githubusercontent.com/assets/5949986/14333292/912294ca-fc13-11e5-9c5d-7194cf13142f.png)

4 - Reduz o botao pra ficar com o mesmo tamanho dos outros.

![image](https://cloud.githubusercontent.com/assets/5949986/14333313/ae6114c6-fc13-11e5-858a-8e66ee753da7.png)

**Comment by LuwkasLima** [comment]
Fala @isaquebrasileiro tamo chegando la, os itens 3 e 4 estao certinhos, so falta mais umas melhorias nos 1 e 2 ok?

1 - Parece que tem um IMPORTANT que joga 24px no padding-top do menu e por esse motivo o texto fica ainda um pouco pr abaixo. Fiz aqui um teste rapidamente usando o Firefox e com 20px fica exatamente como queremos. Pode fazer essa alteracao por gentileza?

![selection_616](https://cloud.githubusercontent.com/assets/5949986/14399719/1c5cfa7e-fdb5-11e5-8e8c-48310a604fb8.png)

2 - A fonte nao parece ser a mesma do Layout. Como fica complicado de achar uma igual, deixa isso pra la e so faz um favor pra mim, tenta esconder a "setinha" que aparece quando o Menu possui Submenu:

![selection_617](https://cloud.githubusercontent.com/assets/5949986/14399748/6dec6118-fdb5-11e5-9d33-8be9e03b19d9.png)

Feito isso aprovo pra mandarmos Brasa! =)

**Comment by isaquemelo** [comment]
@LuwkasLima daqui a pouco o resultado estará pronto.

**Comment by isaquemelo** [comment]
Ainda off no brasaWP.

**Comment by LuwkasLima** [comment]
@isaquebrasileiro ficou beleza pelo que parece, so nao tirou a "setinha", mas pensando bem acho que ta melhor assim mesmo:

![image](https://cloud.githubusercontent.com/assets/5949986/14724508/3cdc6d9e-07dc-11e6-8cb3-02e233b99b10.png)

**Comment by isaquemelo** [comment]
Estranho... Eu tinha tirado. Mas se prefere assim blz =]
