### ISSUE TITLE
Home > Slider de Produtos de uma categoria

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#11]
@matheusgimenez o HTML tá pronto, é só colocar um js para slider. Acho que podemos colocar o mesmo js do Brasa Slider. Mas esse não precisa de administração. Precisamos apenas de um campo no Options para pessoa escolher a categoria (de produtos) que ele quer mostrar alí.

Como acima dele também é um slider, para não ficar estranho, vamos fazer com que esse fique parado, somente rode quando clicarem nas setas.

Qualquer dúvida chama ai.

![slider-produtos](https://cloud.githubusercontent.com/assets/1918474/5882176/29af17f8-a32e-11e4-8b4f-931dc7d53f2b.jpg)

**Comment by everaldomatias** [comment]
@matheusgimenez posso não ter sido claro. Deixa o primeiro slider rodando como estava. E esse que fizemos agora, deixa ele parado (não testei esse). Mas ví que o primeiro ficou parado.

Outra coisa, coloca the_permalink() nesses itens e o thumb também.

**Comment by matheusgimenez** [comment]
Eve.. o buraco é mais em baixo hehe..

Preciso criar um campo no Brasa slider pra configurações.. Segunda faço isso ok?

**Comment by everaldomatias** [comment]
De boa mano.. Depois explica melhor o problema que avaliamos juntos. Não imaginei que precisaria criar mais um campo além do que já tem lá no Options.

Inclusive esse do options, coloca por favor um dropdown das categorias de produtos?

**Comment by matheusgimenez** [comment]
Preciso criar um custom field dentro do cpt do Brasa Slider para colar as configurações.. estão dando conflito.

Não é dificil.. só não sei ainda se o html aceita de boa JSON no atributo data. Mas amanhã de manhã resolvo isso

**Comment by matheusgimenez** [comment]
Resolvi isso no ultimo commit do Brasa Slider.. agora ele aceita configurações! :)

**Comment by everaldomatias** [comment]
Fechando, vou conferir e qualquer coisa abrimos novamente ;)
