### ISSUE TITLE
[URGENTE] Pagina "Services" e Singles nao esta alinhadas com o Layout

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#111]
PEssoal,

A area de widgets da pagina "Services" nao esta alinhada com o Layout. Pelo que entendi, ela precisa de uma area de Widgets exclusiva, ja que possui widgets diferentes das que sao aplicadas no Woo e em News:

http://www.docklandsfurniture.com/services/

SERVICES:

![image](https://cloud.githubusercontent.com/assets/5949986/11790981/4a81ccce-a264-11e5-901e-cbae5c4ce1c5.png)

SINGLE SERVICES:

![image](https://cloud.githubusercontent.com/assets/5949986/11790988/58822648-a264-11e5-8771-66188f295e40.png)

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
@matheusgimenez aqui eu entendi que o menu da Single precisa refletir as outras opções de Services saca?

Ou seja, se na pagina Services eu tenho essas opções:

![image](https://cloud.githubusercontent.com/assets/5949986/11861012/5a137cf8-a441-11e5-888d-d65439dd1d18.png)

Elas deveriam aparecer aqui:

![image](https://cloud.githubusercontent.com/assets/5949986/11861060/e50802e8-a441-11e5-91c8-f6ad61763a7b.png)

Layout:
![image](https://cloud.githubusercontent.com/assets/5949986/11861055/ccdeaeec-a441-11e5-895d-a659b5f6aa28.png)

**Comment by matheusgimenez** [comment]
Isso é um widget de menu, só criar um outro menu, setar ele no widget e boa. :)

**Comment by LuwkasLima** [comment]
OK para ir pra produção!
