### ISSUE TITLE
[Prioridade Baixa] Seção "Hire" não apresenta o conteúdo no formato do Layout

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#112]
Existem 3 layouts para produtos Hire, a "Home" dos produtos Hire, uma segunda Home para um tipo especifico de produto e depois a "lista de produtos" (archive) desse tipo especifico:

Home de Produtos Hire:
![image](https://cloud.githubusercontent.com/assets/5949986/11798546/729c828a-a291-11e5-8656-48411d232a7a.png)

Link: https://drive.google.com/a/brasa.art.br/file/d/0B9gQpzPmhZFkZm95cFlUNjNXX2s/view?usp=sharing

Home de uma categoria de produtos:

![image](https://cloud.githubusercontent.com/assets/5949986/11798820/1601e9f4-a294-11e5-950d-f64c4de71d3e.png)

Lista de Produtos Hire:
![image](https://cloud.githubusercontent.com/assets/5949986/11798557/89def324-a291-11e5-84d9-5021347128c7.png)

Link: https://drive.google.com/a/brasa.art.br/file/d/0B9gQpzPmhZFkenA4VkJzREFYR28/view?usp=sharing

Todo o fluxo e paginas precisam ser revistos com urgencia!

![image](https://cloud.githubusercontent.com/assets/5949986/11798803/ed773200-a293-11e5-904d-e21bd941f78d.png)

**Comment by LuwkasLima** [comment]
Pessoa, verifiquem o comentario do issue #113 onde explico como deve funcionar essa nova página de categorias. Ela deve ser aplicada também para produtos HIRE e NEW do menu principal:

![image](https://cloud.githubusercontent.com/assets/5949986/11913898/d81a6f32-a638-11e5-8a98-89dd3ad5964a.png)

**Comment by everaldomatias** [comment]
@matheusgimenez @LuwkasLima 
Pessoal, eu iniciei o desenvolvimento disso mas travei em uma questão.
Precisamos fazer com que o visitante acesse Hire, o site vai exibir uma página com o atributo "Hire + as categorias que possuírem produtos", criei essa página aqui: http://brasawp.art.br/docklands/hire/ (ainda sem CSS).

O problema é: Quando ele clicar em (por exemplo) Desking, não sei como fazer para que esse archive (http://brasawp.art.br/docklands/product-category/desking/) exiba os posts que estiverem marcados com o atributo Hire.

# 

Pensei em algumas soluções mas gostaria que o Matheus validasse ou nos ajudasse com algum caminho mais inteligente ou com algo que ele já tenha aplicado no próprio Docklands.

Pensei que poderíamos passar um parâmetro pela URL e com o pre_get_posts usar esse parâmetro para filtrar o query.

O que vocês acham?

**Comment by matheusgimenez** [comment]
@everaldomatias preciso me recordar do fluxo disso.. nao lembro :(

**Comment by LuwkasLima** [comment]
@everaldomatias e @matheusgimenez acho que consegui convenser a cliente a usar a pagina intermediara do Woo. Talvez nao vamos precisar mais disso aqui. Vou deixar ON HOLD mais uma vez...

**Comment by LuwkasLima** [comment]
Resolvido com a pagina intermediaria do Woo e o template CASES
