### ISSUE TITLE
[Prioridade Baixa] Seção "Used" não apresenta o conteúdo no formato do Layout

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#113]
Caras, a coisa ta feia, o Used tbm possui diversos layouts de fluxo que nao esta desenvolvidos:

![image](https://cloud.githubusercontent.com/assets/5949986/11798924/0cd854ac-a295-11e5-9b04-2ab4b08d2c69.png)

Home da Used:
![image](https://cloud.githubusercontent.com/assets/5949986/11798931/202c06c0-a295-11e5-8991-02c2a882a1a3.png)

Home de uma categoria de produto Used:

![image](https://cloud.githubusercontent.com/assets/5949986/11798943/37a3966a-a295-11e5-9d47-1c941e9e11ac.png)

**Comment by LuwkasLima** [comment]
@everaldomatias e @matheusgimenez conversei com a cliente e chegamos na conclusao que é necessario desenvolver um dos 2 layouts apresentados nessa sequencia ai em cima. Portanto, vamos desenvolver esse aqui:

https://drive.google.com/a/brasa.art.br/file/d/0B9gQpzPmhZFkaXJmY0o0dUNRNWs/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/5949986/11913856/cb1d8ec8-a637-11e5-9d28-c42b2f336a78.png)

Como vai funcionar?

A pessoa clica em USED no menu principal do site (o preto) e é direcionada a essa página ai em cima que apresenta as categorias de produtos USED que estão disponíveis:

Portanto, as categorias que devem aparecer nessa página são as mesmas do menu lateral:

![image](https://cloud.githubusercontent.com/assets/5949986/11913877/318958b8-a638-11e5-8eaf-2ab187154b85.png)

Atentem ao fato de que só vão aparecer as categorias que possuem produtos USED é claro...

Após a pessoa selecionar uma destas categorias, ela será direcionada a lista de produtos USED + Categoria selecionada.

![image](https://cloud.githubusercontent.com/assets/5949986/11913889/9d5625da-a638-11e5-8062-1aeb319f0e5b.png)

**Comment by LuwkasLima** [comment]
@everaldomatias e @matheusgimenez. O que esta acordado com a cliente eh o que esta ai no comentario acima, ou seja, ao invez de termos 2 paginas intermediarias para apresentar os produtos. Nos vamos ter apenas 1 (Categorias de Produto). Isso eh o que tem que ser desenvolvido...

No entanto, eles estao focando agora nos produtos NOVOS e nao vao usar USED e HIRE **ainda**, mas no futuro proximo sim. Entao vou abaixar a prioridade disso aqui ok? Foquem nos outros temas do e-mail.

**Comment by everaldomatias** [comment]
@LuwkasLima hoje tentei resolver essa issue mas não consegui concluir. @matheusgimenez veja se pode me ajudar, por favor?!

Primeiro, leia toda a descrição e comentários que o Lucas fez. E abaixo comento com o que imaginei que pode ser feito.

Eu criei um template page onde consigo refinar (com muitos querys, infelizmente) até chegar em uma lista de categorias (product_cat) cujo os produtos façam parte também da taxonomia "product_condition" -> term "used", por exemplo.

O problema é, como linkar ele para um archive que mostre apenas posts dessa categoria && used?

**Comment by matheusgimenez** [comment]
@everaldomatias me explica melhor essa duvida eve

**Comment by everaldomatias** [comment]
@matheusgimenez fiz a página (ainda sem CSS) que lista todas as categorias que possuem posts marcados como Hire: Veja no BrasaWP/docklands/hire

Porém, como fazer com que ao clicar em uma dessas categorias, ele só mostre os produtos Hire?
Podemos passar algum parâmetro a mais pela URL e no pre_get_post fazer o query correto?

**Comment by LuwkasLima** [comment]
@everaldomatias e @matheusgimenez acho que consegui convenser a cliente a usar a pagina intermediara do Woo. Talvez nao vamos precisar mais disso aqui. Vou deixar ON HOLD mais uma vez...

**Comment by LuwkasLima** [comment]
Resolvido com a pagina intermediara do Woo e o template da pagina CASES
