### ISSUE TITLE
[Prioridade Media] Página "Delivery And Returns" ou "Terms & Conditions" não está nada igual ao Layout

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#114]
A pagina Terms & Conditions não tem nada a ver com o Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/11799010/c7d7d76e-a295-11e5-89df-267ff6e41ade.png)

![image](https://cloud.githubusercontent.com/assets/5949986/11799023/e6434ae4-a295-11e5-818b-9f565b5c8c7d.png)

**Comment by LuwkasLima** [comment]
@everaldomatias  e @matheusgimenez a cliente me pediu para subir a prioridade desta página, pois ela afeta diretamente as vendas.

**Comment by LuwkasLima** [comment]
Obsevação importante:

Percebam que existem 2 páginas, uma de archives que podem ser CPTs ou apenas uma Página com ACFs e uma outra que é uma Single de cada uma dessas menores.

**Comment by LuwkasLima** [comment]
Precisamos também de uma área de Widget Proprio @everaldomatias e @matheusgimenez:

![image](https://cloud.githubusercontent.com/assets/5949986/11884879/a4a53ec2-a4e2-11e5-897b-b46138fec854.png)

**Comment by LuwkasLima** [comment]
Preciso avaliar antes de enviarmos a produção e fechar a issue.

**Comment by LuwkasLima** [comment]
Pessoal,

Esta muito bom! So faltou a area de Widgets propria pra receber o menu:
![image](https://cloud.githubusercontent.com/assets/5949986/12208458/71755d7a-b612-11e5-80dc-cdf421210698.png)

Nao temos ainda:
![image](https://cloud.githubusercontent.com/assets/5949986/12208523/e1afcec2-b612-11e5-9b80-c5adc313281d.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez precisamos disso para essa semana...

**Comment by matheusgimenez** [comment]
No BrasaWP

**Comment by LuwkasLima** [comment]
@isaquebrasileiro como consigo testar o que foi feito? Eu abri estas paginas mas o menu que aparece nao eh o que esta no widget "Sidebar Conditions":

http://brasawp.art.br/docklands/terms-conditions/

e

http://brasawp.art.br/docklands/terms-conditions/shippings-returns/

**Comment by isaquemelo** [comment]
Lucas... essa o Matheus disse que iria resolver, pois criei o widget e tivemos alguns problemas.

**Comment by matheusgimenez** [comment]
Você não setou a página com o template correto @LuwkasLima

**Comment by LuwkasLima** [comment]
Nao fui eu que criei ela.... =(

Ficou certinho galera, obrigado!
