### ISSUE TITLE
[IMPORTANTE] Página "Testimonial" não está nada igual ao Layout 

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#115]
A pagina Testimonials não tem nada a ver com o layout:

http://www.docklandsfurniture.com/testimonials/

![image](https://cloud.githubusercontent.com/assets/5949986/11799065/589900f2-a296-11e5-852e-bca2fa87cf58.png)

**Comment by everaldomatias** [comment]
http://brasawp.art.br/docklands/testimonials/

Para rodar na produção precisa deletar a página Testimonials, excluir ela da lixeira, criar os Testimonials e carregar a página de Permalinks para o CPT funcionar.
