### ISSUE TITLE
[Prioridade Media] Banners de SPECIALS precisa ser re-feito

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#117]
![image](https://cloud.githubusercontent.com/assets/5949986/11799233/cbe04952-a297-11e5-9138-0a5c8d7cf97d.png)

**Comment by everaldomatias** [comment]
@LuwkasLima os banners são widgets de texto padrão, adiciona uma tag <img> e pronto. Pode colocar link também, é só envolver a tag em <a> ... </a>.

Já os 'Specials', isso eu tinha entendido que seria por categoria, então construí um widget onde a pessoa escolhe a categoria, seta quantos itens ela quer e pronto. No exemplo que coloquei no BrasaWP usei a categoria Storage.

http://brasawp.art.br/docklands/product-category/accessories/cable-management/

**Comment by LuwkasLima** [comment]
@everaldomatias eu entendi como está funcionando, mas estou achando que não é bem essa a utilização...

O que acontece é que precisamos definir quais produtos estão em "destaque" nessa área e na lógica que está, só conseguimos definir a categoria e não produtos específicos.

Hoje estamos utilizando uma categoria e chamando de specials, mas a idéia é que esta área seja populada por produtos "em destaque". Dessa forma precisamos pensar em uma solução onde a pessoa pode escolher quais produtos irão aparecer nesse widget:

**Comment by everaldomatias** [comment]
@LuwkasLima o que conversei com ela é que criaremos uma categoria com o nome "Specials" ou "Em Destaque" e ela marca os produtos com essa categoria para eles aparecerem ai. Ela deu um OK em nossa última reunião, mas se quiser confirmar fique a vontade.

**Comment by LuwkasLima** [comment]
Perfeito hermano, essa era a idéia mesmo. Pode mandar Brasa!

**Comment by LuwkasLima** [comment]
@everaldomatias precisamos disso aqui pra essa semana...

**Comment by everaldomatias** [comment]
![image](https://cloud.githubusercontent.com/assets/1918474/13516316/d0f23b78-e197-11e5-82c4-7321cb792edb.png)

http://brasawp.art.br/docklands/

**Comment by LuwkasLima** [comment]
@everaldomatias infelizmente estamos com um problema com esse widget, veja:

Precisamos que o valor antigo do produto (sem promocao) apareca que nem no Layout.

**Producao:**

![image](https://cloud.githubusercontent.com/assets/5949986/15557087/be5a6d2e-2296-11e6-9d16-7e8bddf8c18a.png)

**Layout:**

![image](https://cloud.githubusercontent.com/assets/5949986/15557030/78855246-2296-11e6-8b4e-f85c9bfa1b1e.png)

**Comment by LuwkasLima** [comment]
@everaldomatias preciso que trabalhe nesse issue.

**Comment by LuwkasLima** [comment]
@matheusgimenez acho que agora temos um probleminha do seu lado.

Os precos NORMAIS e de PROMOCAO foram formatados pelo @everaldomatias, no entanto, percebi que se o produto for VARIAVEL, nao aparece o preco NORMAL. Veja:

![image](https://cloud.githubusercontent.com/assets/5949986/19174827/62a6e302-8bf7-11e6-894e-ac135fd23dd2.png)

![image](https://cloud.githubusercontent.com/assets/5949986/19174837/73ad6d42-8bf7-11e6-83a5-003033dd1def.png)

Precisamos ver como apresentar esse valor do produto DEFAULT somente.

**Comment by LuwkasLima** [comment]
Oi @matheusgimenez,

Encontrei um cenario que nao esta funcionando direito. Veja detalhes:

1 - O Produto aparece com 2 precos (Regular e Promocional) no mesmo valor, no widget:

![image](https://cloud.githubusercontent.com/assets/5949986/20980964/57126adc-bc78-11e6-8499-333578671996.png)

2 - Quando entramos no produto, vejo que ele na verdade nao tem nenhum preco promocional:

![image](https://cloud.githubusercontent.com/assets/5949986/20980999/70fea9b0-bc78-11e6-9a55-4153f81bb4e3.png)

![image](https://cloud.githubusercontent.com/assets/5949986/20981025/81bed220-bc78-11e6-86f5-f5c09a440999.png)

Nesse caso, como ele nao possui preco de promocao, nao precisaria aparecer o preco "cortado" a direita.

**Comment by LuwkasLima** [comment]
Perfeito @matheusgimenez, aprovado pra Producao!

**Comment by LuwkasLima** [comment]
@matheusgimenez achei um pelo mano, tem produtos que nao aparecem com a fracao do preco, veja:

![image](https://cloud.githubusercontent.com/assets/5949986/22122265/eb64a15a-de4c-11e6-8842-17535375e6f5.png)

![image](https://cloud.githubusercontent.com/assets/5949986/22122293/016b2776-de4d-11e6-8fcd-c843edfb9bd7.png)

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
Agora ta OK @matheusgimenez obrigado!

**Comment by LuwkasLima** [comment]
Resolvido!
