### ISSUE TITLE
[URGENTE] Interface de Estoque pode não estar funcionand

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#126]
@matheusgimenez verifica se a interface de atualização de estoque está executando e quando foi a ultima vez que executou. O Cliente enviou um aviso de que havia um produto que aparece como Out of Stock mas que está em estoque na loja:

![image](https://cloud.githubusercontent.com/assets/5949986/11861604/a574fe14-a447-11e5-8a30-4c04643cded2.png)

O produto acima é o Ergonomic Desk | Maestro, SKU 25WHEL16,
que foi importado pela Brasa e que estava funcionando sem problemas até poucos dias atras. 

Nosso site diz que o produto está fora de estoque, mas o site da DAMS mostra que há sim disponibilidade do produto. Chequei as variações do produto e, nelas, as SKUs estão cadastradas normalmente. 

![image](https://cloud.githubusercontent.com/assets/5949986/11861612/bf75dc5c-a447-11e5-93e6-38237097fdee.png)

Erro tb no caso do Compact Home Office Safe | Bisley, SKU SS0721E,:

![image](https://cloud.githubusercontent.com/assets/5949986/11861647/e733bdb8-a447-11e5-9a30-aee846a16177.png)

**Comment by matheusgimenez** [comment]
Primeiro produto nao existe no XML:

![captura de tela de 2015-12-17 12 48 09](https://cloud.githubusercontent.com/assets/4724804/11873146/3b6dfb14-a4c0-11e5-9df6-66145fa1211a.png)

Segundo produto não tem estoque mesmo:

![6n1yfh1](https://cloud.githubusercontent.com/assets/4724804/11873162/4843021c-a4c0-11e5-8990-b77ad8b2cea0.png)
