### ISSUE TITLE
[Baixa Prioridade] Remover botão "Select Option" de Matching Products

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#127]
![image](https://cloud.githubusercontent.com/assets/5949986/11884239/f1ff5e0a-a4dd-11e5-92b0-f0d9a6e56029.png)

**Comment by matheusgimenez** [comment]
Alguém (possivelmente eu) já implementou isso.

**Comment by LuwkasLima** [comment]
@matheusgimenez consegui replicar agora. Veja:

http://brasawp.art.br/docklands/product/cable-control-wave-desk-vivo/

Quando tem um produto com mais de 1 variacao que eh colocado como Up-Sell/Cross-Sell ele aparece com esse botao "Select Options"

**Comment by matheusgimenez** [comment]
Faltava atualizar no BrasaWP. Aparentemente em produção não acontece.

**Comment by LuwkasLima** [comment]
OK
