### ISSUE TITLE
[Prioridade Media] Página FAQ não foi feita!

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#129]
Temos a pagina FAQ?

![image](https://cloud.githubusercontent.com/assets/5949986/11884482/bac3ff84-a4df-11e5-9a86-43c0150c38fc.png)

**Comment by LuwkasLima** [comment]
Subindo essa prioridade aqui, precisamos que isso esteja nas entregas desta semana!

**Comment by matheusgimenez** [comment]
No BrasaWP

**Comment by matheusgimenez** [comment]
( PS: Na produção precisa instalar o Brasa Shortcodes que é o cara que vai gerenciar isso )

**Comment by LuwkasLima** [comment]
@isaquebrasileiro segue meus comentarios:

1 - Existe uma diferenca importante entre o layout e o que foi desenvolvido, vou explicar abaixo:

1.1 - Os itens que estao "colapsados" ou "retraidos" sao na verdade com fundo Branco:

Layout
![image](https://cloud.githubusercontent.com/assets/5949986/14331079/539cfa50-fc09-11e5-8687-5b3d3ccc88cc.png)

Desenvolvido:
![image](https://cloud.githubusercontent.com/assets/5949986/14331098/6a121ebe-fc09-11e5-9b68-cc6011a171e4.png)

1.2 - Itens que estao ABERTOS, estes sim, sao azuis:

Layout
![image](https://cloud.githubusercontent.com/assets/5949986/14331138/8af5a6a0-fc09-11e5-8be7-6e39c48a20a7.png)

Desenvolvido: Estao Laranja...
![image](https://cloud.githubusercontent.com/assets/5949986/14331149/99bb3dd0-fc09-11e5-9df4-5eed1231a859.png)

1.3 - O layout expressa que existem 3 niveis nesse itens. Nivel 1 eh ele fechado e BRANCO, Nivel 2 eh ele fechado e BRANCO (com o "+" em LARANJA) e o Nivel 3 eh ele aberto e LARANJA:

![image](https://cloud.githubusercontent.com/assets/5949986/14331193/db378cd2-fc09-11e5-8e6e-2d1f4dc40dcc.png)

@matheusgimenez vc sabe se conseguimos criar niveis com os shortcodes?

**Comment by LuwkasLima** [comment]
@isaquebrasileiro esqueci de perguntar umas coisas . 

2 - O widget que vc colocou na pagina eh qual? Existe uma area de Widget so pra pagina FAQ tbm?

![image](https://cloud.githubusercontent.com/assets/5949986/14331376/a5f9f48c-fc0a-11e5-9dc3-56f2ac9ce559.png)

Consegue meter uma margem aqui pra baixar os botoes?

3 - Existe uma area: "Leave a Question" no layout. Como colocamos?

![image](https://cloud.githubusercontent.com/assets/5949986/14331429/d46fd714-fc0a-11e5-9f70-1caa159f255e.png)

**Comment by LuwkasLima** [comment]
Inclui um formulario pra voce ver como ficar e dar aquele tapa CSS:

![image](https://cloud.githubusercontent.com/assets/5949986/14332039/75959fb4-fc0d-11e5-88cb-13410e15f239.png)

@isaquebrasileiro pelo que entendi, pra vc criar as classes desses elementos e dividir eles em divs pra poder cria ro CSS precisa ser pelo Contact Form 7. Conversa com o @matheusgimenez que ele vai te explicar melhor se esse for o caso..

**Comment by LuwkasLima** [comment]
@isaquebrasileiro nao entendi o que foi feito aqui? Pode me explicar se todos os pontos acima foram feitos?

**Comment by isaquemelo** [comment]
@LuwkasLima não endendo! Esta tudo feito sim. Todos os pontos foram feitos no dia 06/04.
![capturar](https://cloud.githubusercontent.com/assets/7103838/14393465/8efa125a-fd9d-11e5-8512-4f0dd25fb2c3.PNG)

**Comment by isaquemelo** [comment]
Em relação aos icones daqui a pouco concerto eles. Na verdade eu tirei eles no meu ambiente local já que no layout não tínhamos nada semelhante.

**Comment by LuwkasLima** [comment]
@isaquebrasileiro desculpe aqui, o @matheusgimenez nao tinha subido no ambiente de dev pra testes ainda, por isos fiz a pergunta. Precebi so depois que comentei..

Ficou perfeito cara! Muito bom o trabalho...

**Comment by LuwkasLima** [comment]
@matheusgimenez e @isaquebrasileiro 

2 coisas que preciso da ajuda de voces:

1 - A area de comentarios nao esta apresentando o CSS que o @isaquebrasileiro fez. Podem checar porque? (Ambiente de [producao](http://www.docklandsfurniture.com/frequently-asked-questions-faq/) - )

![image](https://cloud.githubusercontent.com/assets/5949986/15087102/786a2204-13ab-11e6-8633-0aa39f92629a.png)

2 - Preciso que quando Algum Plugin seja utilizado, voces me expliquem aqui na Issue. Assim eu sei que tenho que ativa-lo em producao pra funcionar. Sempre deixem bem explicado o que precisa ser feito para funcionar (nesse caso, tive que instalar o Brasa Shortcodes e criar um formulario do Contact Form...)

**Comment by LuwkasLima** [comment]
Esquece, resolvi aplicando o Template...Daaahhnn

De qualquer jeito, o comentario 2 eh valido =)

**Comment by LuwkasLima** [comment]
Ops achei um problema @isaquebrasileiro! =D

O titulo ta "hardcoded", deveria puxar o titulo do post. Pode por gentileza fazer essa correcao?

![image](https://cloud.githubusercontent.com/assets/5949986/15087146/d6dede42-13ab-11e6-8ecf-02721427f8e6.png)

Obrigado!

**Comment by isaquemelo** [comment]
@LuwkasLima desculpa a demora! Como todas as issues já haviam sido fechadas achei que tinha terminado. Ainda hoje atualizo.

**Comment by LuwkasLima** [comment]
@isaquebrasileiro tranquilis!
