### ISSUE TITLE
[Prioridade Media] Criar Página "Guide & PDF"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#130]
![image](https://cloud.githubusercontent.com/assets/5949986/11884526/04df22ce-a4e0-11e5-92f8-6e5d3eb79a30.png)

**Comment by matheusgimenez** [comment]
No BrasaWP.

Criei como um page-template. Chama Guides & PDFs, tem um widget proprio pra ele na esquerda.

O posts exibidos ali são pages filhas dela mesmo.

**Comment by LuwkasLima** [comment]
OK @matheusgimenez, vou mudar o label pra "Para Validar"

**Comment by LuwkasLima** [comment]
@matheusgimenez voce precisa ver porque o Template nao esta em ambiente de producao. Por favor da uma olhada pra que eu possa fechar a issue.

Obrigado!

**Comment by LuwkasLima** [comment]
Ja encontrei o template em producao.
