### ISSUE TITLE
[Rova Requisicao] Modificar Template de Pedido

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#131]
@everaldomatias vamos criar um template bonitinho para o Docklands, simples, somente com o logo e uma cores que combinem, nada mais. Eu ja fiz minha parte modificando a escrita do rodapé...rs

![image](https://cloud.githubusercontent.com/assets/5949986/11909718/61e68540-a5b0-11e5-9367-cfb9ad460292.png)

**Comment by everaldomatias** [comment]
@LuwkasLima apliquei o logo, veja se é isso que deseja:

![image](https://cloud.githubusercontent.com/assets/1918474/14548052/d8a51e22-0289-11e6-84b5-e8552e3a0229.png)

**Comment by LuwkasLima** [comment]
Perfeito, ela vai gostar...obrigado!
