### ISSUE TITLE
[Prioridade Baixa] Ícones de Redes Sociais em "NEWS"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#132]
Oi Pessoal,

Precisamos habilitar os botões de redes sociais no Archive de News e no Single News:

![image](https://cloud.githubusercontent.com/assets/5949986/11913740/375b790a-a634-11e5-9695-7ba61f78b977.png)

![image](https://cloud.githubusercontent.com/assets/5949986/11913742/43db7842-a634-11e5-81ac-4a6cad791077.png)

**Comment by LuwkasLima** [comment]
Já vi que é pelo Jetpack então estou conversando com a cliente para ela criar uma conta e configuramos isso.

**Comment by LuwkasLima** [comment]
@matheusgimenez configurei o jetpack em producao, mas precisamos colocar os botoes de compartilhamento para aparecerem no archive:

![image](https://cloud.githubusercontent.com/assets/5949986/12398193/a51104d2-bdd7-11e5-9a73-6711b4cdb5af.png)

Como no layout:

![image](https://cloud.githubusercontent.com/assets/5949986/12398208/bcaa51fc-bdd7-11e5-9af0-af3a013dd7af.png)

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
OK!
