### ISSUE TITLE
[Prioridade Media] Area abaixo da lista de produtos não bate com Layout

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#134]
Oi pessoal,

Abaixo da listagem de produtos, precisamos ter o seguinte: "Matching Produtcs" e "Recent Viewed Items" (no entanto, não coloqueo o Matching Products, somente o "Recent Viewed" ao lado do Side Bar:

Além disso, precisamos aplicar um CSS na paginação pra ficar igual ao Layout.

![image](https://cloud.githubusercontent.com/assets/5949986/11914018/51112830-a63a-11e5-9673-b373ef99a944.png)

Hoje está assim:

![image](https://cloud.githubusercontent.com/assets/5949986/11914021/69aafb5a-a63a-11e5-9110-c12296b38ea4.png)

**Comment by matheusgimenez** [comment]
No BrasaWP

**Comment by LuwkasLima** [comment]
OK! Perfeito @isaquebrasileiro!
