### ISSUE TITLE
[URGENTE] Usuário Seller

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#136]
Verificar permissões.

• Alterar valor;
• Alterar estoque;
• Chat (Atualmente 4 vendedores; no primeiro momento apenas 2 cuidarão do chat);
• Não deleta nem cadastra produtos;

**Comment by LuwkasLima** [comment]
@everaldomatias categoriza isso como PRIORIDADE MEDIA ou IMPORTANTE (dependendo da expectativa do cliente)

**Comment by LuwkasLima** [comment]
Classifiquei como IMPORTANTE pois precisa estar OK pra eles comecarem a trabalhar..

**Comment by matheusgimenez** [comment]
@LuwkasLima sobre alterar valor.. ngm me falou disso antes e complica se pensarmos em produtos c/ variações

**Comment by matheusgimenez** [comment]
@matheusgimenez alias, inclusive stock complica.. como ficam os produtos variaveis?

**Comment by LuwkasLima** [comment]
@everaldomatias voce saberia nos dizer porque estamos utilizando um modal para editar produtos como Seller? - Precisamos disso pra seguir com a solucao...

**Comment by matheusgimenez** [comment]
@LuwkasLima como ficou isso? precisamos resolver tbm

**Comment by LuwkasLima** [comment]
@matheusgimenez fiquei de conversar com a cliente sobre essa issue. Assim que retomar, ela tem que ser uma das primeiras ok?

**Comment by LuwkasLima** [comment]
@matheusgimenez e @everaldomatias eu criei um usuario "lucas" e coloquei a Role "Seller" e ele nao possui acesso ao Dashboard. Voces nao haviam dito que essa role tem acesso ao Dashboard para atualizacao dos produtos?

![image](https://cloud.githubusercontent.com/assets/5949986/12277142/7ad3fa04-b93f-11e5-9b07-ee6b83ecf3be.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez manda bala aqui por gentileza, precisamos disso pra ontem infelizmente! =)

**Comment by LuwkasLima** [comment]
@matheusgimenez ta perfeito mano! Podemos mandar Brasa!
