### ISSUE TITLE
Problema com CSS

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#14]
Equipe ( @willowmagrini @matheusgimenez @diegorojas ), queria pedir a ajuda de todos (que possível) para me ajudarem a procurar onde estou errando nesse HTML/CSS, vejam a imagem abaixo:

![erro-dock](https://cloud.githubusercontent.com/assets/1918474/5909493/40d1e5c0-a598-11e4-9076-8f6370684b85.jpg)

Vejam que os primeiros boxes estão alinhados perfeitamente, mas justamente nos que estão abaixo, com as imagens, ele perde alguma margem ou sei lá o que e está ficando desalinhado. Podem me ajudar, ao menos tentando descobrir o que poderia ser :)

Segue o /dev: http://brasawp.art.br/docklands/

Valew.

**Comment by everaldomatias** [comment]
Alguém @diegorojas @LuwkasLima @willowmagrini @matheusgimenez ?

**Comment by diegorojas** [comment]
Eve, detectei o problema é coisa boba do tamanho da imagem cara.. Vai precisar colocar pelo menos alguns atributos para a img especifica da classe .banner por exemplo.

Coloca o  img {   width: 100%; } em algum lugar que você já vai ver o seu grid bonitinho, com os alinhamentos e espaçamentos corretos

**Comment by everaldomatias** [comment]
Smack o/
