### ISSUE TITLE
[IMPORTANTE] Paginas do Checkout da Seção "Hire" 

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#141]
@matheusgimenez essa aqui é bucha:

A seção Hire Business não será venda online e sim Add to Enquire para que a Docklands prepare uma Quote e retorne para o cliente. Segundo o Layout, temos 3 etapas:

1 - Incluir no Carrinho:
![image](https://cloud.githubusercontent.com/assets/5949986/12183899/81a85bc2-b557-11e5-88e8-d8f89e389946.png)

Link: https://drive.google.com/drive/folders/0B9gQpzPmhZFkN0RmbkJqanFOS0k

2 - Checkout (com envio de Enquire por e-mail):
![image](https://cloud.githubusercontent.com/assets/5949986/12183915/9f1dc232-b557-11e5-978b-bdca5490e33c.png)

Link: https://drive.google.com/drive/folders/0B9gQpzPmhZFkN0RmbkJqanFOS0k

3 - Pagina de conclusção do Quote:
![image](https://cloud.githubusercontent.com/assets/5949986/12183933/c309ca7e-b557-11e5-9249-67a8b862fdfd.png)

Link: https://drive.google.com/drive/folders/0B9gQpzPmhZFkN0RmbkJqanFOS0k

Portanto, precisaremos criar essas 3 páginas para produtos HIRE somente.

**Comment by LuwkasLima** [comment]
@matheusgimenez hoje em conversa com a cliente, ela indicou que muito provavelmente irao utilizar esta funcionalidade de Quotation tambem na secao "USED", ou seja, nao somente da Hire.

No estagio que esta, o plugin pode ser aplicado tanto em uma secao como em outra?

Obrigado!

**Comment by matheusgimenez** [comment]
Sim

**Comment by LuwkasLima** [comment]
@matheusgimenez tentei fazer o teste e nao me parece estar funcionando. Nao encontrei os botoes de "Request a Quote" no produto Hire, nao vi nenhum plugin instalado pra isso e nenhuma opcao nos produtos pra eu marcar como "Quotation". Pode verificar se a ultima versao esta no brasawp e me explicar brevemente como fazer o teste?

**Comment by matheusgimenez** [comment]
De fato ele não estava instalado mesmo..

Adiciona ele ao carrinho e testa:

http://brasawp.art.br/docklands/product/quote-product/

**Comment by LuwkasLima** [comment]
@matheusgimenez consegui testar! Vamos la aos pontos que encontrei:

1 - Quando escolho um produto de "Quote" e nao escolho de "Comprar", precisamos que apenas apareca 1 dos boxes (pra nao confundir o cliente). Ou seja, somente o de "Request a Quote":
![image](https://cloud.githubusercontent.com/assets/5949986/13685544/8e27ce4a-e6d6-11e5-822a-91e377875daa.png)

2 - O box de request a Quote tambe precisa ter espaco para o Cupom de Desconto (eu realmente nao sei dizer se isso faz sentido, pois nao conheco o modelo de negocio da Docklands). Mas como esta no Layout, prefiro fazer:
![image](https://cloud.githubusercontent.com/assets/5949986/13685521/763679da-e6d6-11e5-8fe3-1d8f0d3590d1.png)

![image](https://cloud.githubusercontent.com/assets/5949986/13685561/9d7a140c-e6d6-11e5-9b65-d2d44cba842a.png)

3 - Pergunta: Na pagina de "Quote Details", se eu ja estiver logado, ele aparece automaticamente minhas informacoes preenchidas no formulario?
![image](https://cloud.githubusercontent.com/assets/5949986/13685635/fec85412-e6d6-11e5-946b-bb1e88e958b0.png)

4 - E se eu nao estiver logado, nao consigo abrir a pagina para fazer login:
![image](https://cloud.githubusercontent.com/assets/5949986/13685796/0607ffb0-e6d8-11e5-98f6-45b1d41e9065.png)

5 - Deveriamos trocar "Your Order" pra "Your Quote"? Podemos colocar a info inteira do produto, com foto, nome, quantidade e preco?
![image](https://cloud.githubusercontent.com/assets/5949986/13685752/b8d181ee-e6d7-11e5-93fe-c75904ec17c7.png)

# 

Outro ponto bem complicado:

6 - Eu adicionei um produto de "Compra" e outro de "Quote" e cliquei em "Proceed to Checkout"

![image](https://cloud.githubusercontent.com/assets/5949986/13685941/c864ecb2-e6d8-11e5-95cb-166656dc8675.png)

Dai eu completei a compra e adivinha? O Carrinho esvaziou...

![image](https://cloud.githubusercontent.com/assets/5949986/13685955/e6aaccf0-e6d8-11e5-8ce4-66139e8f9a98.png)

Eu estou pensando se existiria algum cenario onde a pessoa fizesse a cotacao de um produto e a compra de outro. Como estamos dando essa possibilidade, acredito que seja melhor pensarmos em uma solucao simples e efetiva. 

A solucao mais plausivel pra mim seria que o carrinho mantivesse o produto que nao finalizou a compra. Mas nao sei quao complicado seria isso. Consegue me ajudar?

Link pro Layout: https://drive.google.com/drive/folders/0B9gQpzPmhZFkN0RmbkJqanFOS0k

**Comment by LuwkasLima** [comment]
@matheusgimenez nenhum dos itens acima foi resolvido... =(

**Comment by matheusgimenez** [comment]
O ponto 1 eu cheguei no seguinte resultado:

![screenshot-localhost 2016-03-12 17-15-52](https://cloud.githubusercontent.com/assets/4724804/13725067/3db334b2-e876-11e5-8ffa-c59c8bb1457a.png)

Não sei se eu deveria remover a palavra "Cart" ali de cima, pq isso é o titulo da página.. O que acha?

Ps: enviei o ponto 1 ao repo do plugin.

**Comment by matheusgimenez** [comment]
Ponto 2: Já resolvido

Ponto 3: Sim, preenche.

Ponto 4: Resolvido

Ponto 5: resolvido

Ponto 6: já tinhamos conversado anteriormente

**Comment by LuwkasLima** [comment]
Oi @matheusgimenez segue o resutlado dos meus testes:

1 - Ainda existe uma quebra (titulo "REQUEST A QUOTE":

![image](https://cloud.githubusercontent.com/assets/5949986/13732842/46c5e364-e958-11e5-9502-2b196c92967b.png)

2 - Area de Cupon de Desconto:

Ficou perfeito o posicionamento do campo de cupom, seguindo o padrao. No entanto, quando eu aplico um desconto, nao me aparece nada, so a mensagem acima "Coupon Code successfully applied"

![image](https://cloud.githubusercontent.com/assets/5949986/13732719/018948e6-e957-11e5-82cc-39957ca59b35.png)

Isso acontece porque voce retirou o box "Checkout Options". Ele deve constar, inclusive com info de Delivery, Discontos e Imposto (VAT):

![image](https://cloud.githubusercontent.com/assets/5949986/13732758/678136a4-e957-11e5-9670-bca6248997d9.png)

![image](https://cloud.githubusercontent.com/assets/5949986/13732747/52e38e04-e957-11e5-969d-2b9c57ffc351.png)

3 - PERFEITO!

4 - Ainda nao faz nada (ele joga a tela pra cima):

![image](https://cloud.githubusercontent.com/assets/5949986/13732808/e5c6f9ea-e957-11e5-9a04-1f5b1eba6942.png)

5 - Ficou Perfeito cara!

![image](https://cloud.githubusercontent.com/assets/5949986/13732790/aedcb5b4-e957-11e5-8ecb-86abb7c52a15.png)

6 - Exato. Farei mais alguns testes...

7 - (achei mais uma coisa) O formulario de Shipping ta me pedindo Password (nao posso fazer checkout como Guest?) e nao apresenta o campo "Zip Code":

![image](https://cloud.githubusercontent.com/assets/5949986/13732947/f9dc0f0e-e959-11e5-9c2b-ddfcaad51f19.png)

**Comment by matheusgimenez** [comment]
Acho que fixei todos os pontos.. to enviando pro brasaWP

**Comment by LuwkasLima** [comment]
Seguem meus comentarios:

1 - Ainda nao esta OK no **Chrome**. O Firefox parece que ta ok:

**Chrome:**
![image](https://cloud.githubusercontent.com/assets/5949986/13993278/b2cb057a-f0ed-11e5-8502-9a200fc3c71b.png)

**Firefox:**
![image](https://cloud.githubusercontent.com/assets/5949986/13993507/afed439e-f0ee-11e5-9dda-e2784d7318d9.png)

2 - esta OK!

4 - Ficou certinho!

6 - Fiz 2 testes e ele ZERA automaticamente o carrinho sempre que termino o checkout pro produto "de Compra", retirando o de Quotation do carrinho. Se nao existe outra forma de resolver, a unica solucao que eu vejo eh colocarmos uma Mensagem que nao permite ninguem colocar no carrinho produtos de venda e de quotation juntos.

Algumas sugestoes:

1 - Quando alguem seleciona um produto de QUOTE, ao invez de ele ir pro carrinho, ele vai direto para o checkout, pedindo as infos do usuario. Assim a pessoa eh obrigada a terminar a cotacao antes de continuar navegando no site (podemos inclusive mandar ele de volta pra onde ele estava antes de comecar o processo)

2 - Bloqueamos a inclusao de produtos Quote e de Compra juntos no carrinho com uma mensagem: "Caro cliente, por gentileza termine sua cotacao antes de iniciar uma compra. Agradecemos sua compreensao". O que nao eh ruim, mas nao eh a melhor solucao do mundo pra quem ta comprando...

![image](https://cloud.githubusercontent.com/assets/5949986/13993839/09005fc4-f0f0-11e5-85d8-77ead3f468a2.png)

7 - Ainda esta acontecendo. Ele pede o Password e pede ZipCode pra calcular o shipping, no entanto, nao existe o campo de Zip Code (voce o escondeu?)

![image](https://cloud.githubusercontent.com/assets/5949986/13993755/afe19674-f0ef-11e5-9ccd-f12a897ca54f.png)

**Comment by matheusgimenez** [comment]
No BrasaWP

**Comment by LuwkasLima** [comment]
1 - No **Firefox** como esta agora:

![image](https://cloud.githubusercontent.com/assets/5949986/14329279/53fb0db0-fc00-11e5-95bb-aa2a2cb0557b.png)

Olha o que acontece quando coloco 2 produtos de compra e 1 de Quote:

![image](https://cloud.githubusercontent.com/assets/5949986/14330041/29905f0e-fc04-11e5-8c82-254590e85b49.png)

6 - Funcionando perfeitamente! Muito bom @matheusgimenez 

# 7 - OK!

Novos Pontos:

8 - Quando vou para o Check out (sem estar logado) e clico em "_**Returning customer? Click here to login**_" a caixa de dialogo abre e depois fecha sozinha...

![image](https://cloud.githubusercontent.com/assets/5949986/14330123/a37f6774-fc04-11e5-818f-0f11a250721f.png)

![image](https://cloud.githubusercontent.com/assets/5949986/14330144/c24a1028-fc04-11e5-94c9-d2571703383b.png)

**Comment by matheusgimenez** [comment]
Acho que fixei todas.

Verificar no brasaWP

**Comment by LuwkasLima** [comment]
1 - Perfeito!
8 - Perfeito!

**Novos Pontos:**
Cara!, quase passou, mas agora estamos a 1 ponto...

9 - Eu coloquei 2 produtos de Compra e 1 de Quote pra fazer o teste do item 1 e depois fiz a compra dos 2 produtos pra testar o item 8. Ateh ai tudo certo, terminei a compra e quando cliquei pra abrir o carrinho de novo ele aparece assim:

![selection_620](https://cloud.githubusercontent.com/assets/5949986/14400219/7a6eccbe-fdba-11e5-9fd8-8d3106d8bd3d.png)

**Comment by matheusgimenez** [comment]
Fixed!

**Comment by LuwkasLima** [comment]
Aee carai!!....Fechamos isso cara..

Vmaos lancar esse Plugin agora mesmo! =D

**Comment by LuwkasLima** [comment]
Epaa!!...Achei mais uma coisa malandro!...kkkkk

![image](https://cloud.githubusercontent.com/assets/5949986/14576064/b3d62ef4-032b-11e6-9ff6-4c1197042cb7.png)

1 - Mobile Versio (Checa o codigo do Eve pro carrinho normal, ficou top...)
2 - Ta aparecendo 2 botoes de Checkout.

**Comment by matheusgimenez** [comment]
No BrasaWP

**Comment by LuwkasLima** [comment]
@matheusgimenez pra deixar redondo, so da um tapa nessa separacao do titulo ai por favor, pra ficar igual a do CART:

![image](https://cloud.githubusercontent.com/assets/5949986/14724401/7fa118e2-07db-11e6-857f-0ee20df9b170.png)

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
Belezura irmao, a versao Beta do plugin esta pronta! Hackaton pra montar imagem e descricao pra publicacao!!
