### ISSUE TITLE
[Prioridade Baixa] Video e Banner da Home estao aparecendo no Archive

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#146]
Pessoal,

Na archive de produtos, quando selecionamos uma categoria de produtos, o Banner e Video da Home page estao aparecendo. No entanto, nos layouts estes 2 elementos nao devem aparecer:

![image](https://cloud.githubusercontent.com/assets/5949986/12297927/17f69086-b9d5-11e5-9bbc-9e58942ee80f.png)

Exemplo: http://www.docklandsfurniture.com/product-category/desks/?swoof=1&product_condition=new

![image](https://cloud.githubusercontent.com/assets/5949986/12297980/6dad2b5c-b9d5-11e5-8061-04fe95ebadc9.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez consegue me confirmar se esse foi feito?

**Comment by matheusgimenez** [comment]
Olhei no codigo e no meu site aqui local e parece OK!

**Comment by LuwkasLima** [comment]
Beleza, estou mudando o Label "Para revisao" entao, pra eu me programar...

**Comment by LuwkasLima** [comment]
@matheusgimenez segundo o layout, ainda precisa aparecer o "New Arrivals". Portanto nao esta completo, no entanto, eu vou deixar assim pois acredito que nao precisa existir. Mas precisamos ficar atentos a estes detalhes...
