### ISSUE TITLE
[Prioridade Baixa] Plugin "Duplicator" em ambiente produtivo

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#148]
Pessoa, estamos com esse plugin ativado em producao. Podemos desativa-lo?

![image](https://cloud.githubusercontent.com/assets/5949986/12397893/ba220d46-bdd5-11e5-918a-341a1800f97b.png)

**Comment by matheusgimenez** [comment]
Remove, eu instalei mas nem rola usar pq ele limita o tamanho e o docklands ultrapassa esse tamanho.

Tinha instalado pra trazer o site pra localhost, mas acabei fazendo na unha.

**Comment by LuwkasLima** [comment]
Feito! Obrigado @matheusgimenez
