### ISSUE TITLE
Link Top

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#15]
Matheus coloquei aquele link Top no site mas ele deve funcionar como os mais populares,  que é:

Só aparece depois de rolar tantos pixels;
Sobe a página com efeito suave.

**Comment by matheusgimenez** [comment]
Que link?

**Comment by everaldomatias** [comment]
![top](https://cloud.githubusercontent.com/assets/1918474/5957476/36cf8c34-a7a1-11e4-90de-8e589567f030.jpg)

Este...
