### ISSUE TITLE
Habilitar Compressão GZIP no servidor de hospedagem

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#152]
Verificar com a hospedagem do Docklands e habilitar a opção de compressão GZIP do website.

Caso não seja possível via servidor fazer via plugin no WP. OU também via HTACESS

Aqui os 3 meios de se fazer esta operação

http://softstribe.com/wordpress/enable-gzip-compression-in-wordpress/

**Comment by diogosp** [comment]
Se for usar o W3 Total cache ele já tem uma opção pra isso. @matheusgimenez @LuwkasLima

**Comment by LuwkasLima** [comment]
@diogosp perfeito!

Qual eh a forma mais segura? Se o plugin da conta e nao tem nenhum ponto contrario, vamos com ele. Se eh melhor via HTACESS ou server, entramos em contato com o servidor..

**Comment by diogosp** [comment]
@LuwkasLima Eu entendo que seria melhor habilitar no SERVER.

**Comment by diogosp** [comment]
FEITO via W3 TOTAL CACHE
