### ISSUE TITLE
Customizar o .HTACCESS para expiração de arquivos

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#153]
Customizar o .HTACCESS do website para melhorar o SEO.
Quando habilita a expiração de arquivos o cache do navegador é utilizado, fazendo com que o load do server seja menor.

Aproveitar cache do navegador.
Vi que neste ponto é questão de preconfigurar um período de tempo para expirar os conteúdos, pq sem isso o cache do navegador não fica habilitado e assim ele repete as operações todas novamente quando o usuário entra novamente. A melhor saída que vi é editar o .HTACESS com algumas pre-configurações para cada tipo de arquivo. LINK com exemplo

http://www.valuehost.com.br/blog/como-aproveitar-o-cache-do-navegador/

**Comment by LuwkasLima** [comment]
@diogosp o plugin resolve isso ou esse eh uma config manual mesmo?

**Comment by diogosp** [comment]
FEITO. via W3 Total Cache.
