### ISSUE TITLE
Habilitar Minify/Combine de JS e CSS - e também Async

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#154]
Compactação CSS/JS/HTML

Habilitar dois plugins:
**Better WordPress Minify
Speed Booster Pack**

eles farão a compactação dos JS, CSS e também colocarão os scripts no Footer e no modo async para agilizar o load das páginas (principalmente no celular).

@LuwkasLima como eu pontuei no email esta operação não vai salvar taaaantos Kbs. é só pra deixar de default mesmo. Os scripts já estão bastante customizados e o site é gigante pra conseguir resolver via minify.

**Comment by diogosp** [comment]
@matheusgimenez @LuwkasLima 
Matheus então vamos com o W3 Total Cache aqui? (certamente ele é mais atualizado constantamente do que os que indiquei aí)

**Comment by LuwkasLima** [comment]
Vamos de W3 entao!

**Comment by diogosp** [comment]
FEITO. Via W3 Total Cache

**Comment by diogosp** [comment]
Fechou galera, expliquei no email que esta parte do Minify eu fiz com o Speed Booster pq ele fez melhor o trampo.
