### ISSUE TITLE
[Baixa Prioridade] Botoes Sociais em Baixa Definicao!

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#155]
Oi Pessoal,

Segundo a cliente, os botoes de midia social estao com baixa resolucao. Voces sabem me dizer onde encontraram essas imagens? Foi eles que nos enviaram, usamos de um template ou encontramos na internet?

![image](https://cloud.githubusercontent.com/assets/5949986/13018487/63130730-d18f-11e5-9c79-ac4a47512745.png)

**Comment by matheusgimenez** [comment]
No brasaWP.

**Comment by LuwkasLima** [comment]
1 - @isaquebrasileiro rola deixar o icone do Facebook no Rodape com "radio" (bordas arredondadas) pareciso com os outros 3?

![image](https://cloud.githubusercontent.com/assets/5949986/14330755/ac2073e8-fc07-11e5-885b-1e5d31415858.png)

2 - O jogo de icones tem somente esse icone do Twitter? Nao tem o do passarinho? ou um com o T menor?

![image](https://cloud.githubusercontent.com/assets/5949986/14330854/0d77583c-fc08-11e5-8f2f-e3fd332394ed.png)

De resto esta perfeito!

**Comment by LuwkasLima** [comment]
Beleza @isaquebrasileiro, obrigado!
