### ISSUE TITLE
[IMPORTANTE] Filtro de Produtos nao esta funcionando

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#157]
Pessoal, o filtro de produtos nao esta executando filtros e as configuracoes estao corretas no Dashboard. Eu julgo nque talvez tenha algo a ver com o W3 total cache.

http://www.docklandsfurniture.com/advanced-search/?min_price=5&max_price=15

Abra o link acima e tente filtrar por qualquer uma das opcoes...

@matheusgimenez e @diogosp por gentileza verifiquem isso ateh sexta dia 19/02

Obrigado!

**Comment by matheusgimenez** [comment]
Não consegui solucionar esse. O erro que o script alerta no console eu resolvi, mas sempre ele fica dando um erro mais abaixo, ou seja, eu arrumo um e surge outro.

Deve ser algo relacionado ao minify ou algo assim.. mas não sei o que :(

**Comment by LuwkasLima** [comment]
To bastante preocupado com esse ponto, porque está acontecendo em Produção e impactando diretamente a experiência de quem acessa a loja.

Você tentou desativar os plugins de SEO pra ver se volta?

**Comment by matheusgimenez** [comment]
Desativando o plugin **Speed Booster Pack** o filtro volta a funcionar. Deixei desativado, mas precisamos rever a configuração desse plugin ou instalar outro, creio.

**Comment by diogosp** [comment]
@matheusgimenez eu acho que precisamos apontar pro plugin qual .JS específico não pode entrar no minify aí. Qual é exatamente este que controla ali a busca avançada?

**Comment by diogosp** [comment]
@LuwkasLima e @matheusgimenez bom, realmente era o **Speed Booster** aparentemente ele faz um trabalho bastante drástico com o DEFER dos JS e joga tudo no Footer. Acontece que isto está fazendo os JSs de filtros (que entendi serem do próprio Woo e são divididos em vários) nao serem lido corretamente.

Eu fiz um outro caminho agora. Reativei os MINIFY e o Async via W3 Total Cache e funfou numa boa. YEAH!

agora, tem uma coisa que precisa ser explicada pro cliente:
- O site tem estruturas avançadas e carrega bastante JSs. Portanto não dá pra minificar tudo na força bruta. A complexidade do site carrega peso obrigatoriamente.
- Se o cliente for lá no PageSpeed novamente ele verá que o Google ainda alerta pra um erro a ser corrigido (coisa que com o Booster eu conseguia retirar). MAS não é um erro grave pois vc vê que ele conseguiu minificar corretamente e só restaram dois arquivos (um JS e um CSS agrupados) criados pelo próprio W3. É normal, ta tranquilo, mas aparece como algo a ser corrigido.

Mas está consertado galera.

<img width="832" alt="captura de tela 2016-02-20 as 13 27 43" src="https://cloud.githubusercontent.com/assets/5107285/13197481/e2841620-d7d5-11e5-82a6-268da9b4d945.png">

**Comment by LuwkasLima** [comment]
Muito Obrigado pessoal!...Vou colocar meu nome nessa issue pra poder explicar a cliente e baixar a prioridade para IMPORTANTE.

Muito obrigado mesmo!

**Comment by LuwkasLima** [comment]
Resolvido!
