### ISSUE TITLE
[IMPORTANTE] Dados de FTP com conta "codeispoetry.info"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#158]
@matheusgimenez verificando algumas configuracoes no site do Docklands, percebi que temos a seguinte informacao no site em Producao, muito provavelmente vinda do ambiente de desenvolvimento:

![image](https://cloud.githubusercontent.com/assets/5949986/13300546/4edbde42-db06-11e5-84bd-09a073f233f0.png)

**Comment by matheusgimenez** [comment]
WTF. Desde quando ta com esses dados ai?

**Comment by LuwkasLima** [comment]
Nao sei, mas deve ser desde que migramos...

**Comment by LuwkasLima** [comment]
@matheusgimenez ouve mudanca de codigo aqui?

**Comment by matheusgimenez** [comment]
@LuwkasLima sim

**Comment by LuwkasLima** [comment]
@matheusgimenez fiz um teste rapido aqui e encontrei uma discrepancia entre o arquivo XML do servidor da DAMS e o estoque do SKU "BOXULT1" no site em ambiente de dev, veja:

Arquivo do dia de hoje (07/03/3026):
![image](https://cloud.githubusercontent.com/assets/5949986/13580996/620f5e40-e46a-11e5-9a60-a1b7425f14e6.png)

SKU no site:

![image](https://cloud.githubusercontent.com/assets/5949986/13581027/83b41bb2-e46a-11e5-8c2b-c8989a9c0233.png)

### Outro Exemplo

SKU: 1001-0100

XML:
![image](https://cloud.githubusercontent.com/assets/5949986/13581069/c285a6f8-e46a-11e5-9e54-164ae663b2fe.png)

Produto no site:
![image](https://cloud.githubusercontent.com/assets/5949986/13581087/d651f15a-e46a-11e5-80de-2299df3d4b60.png)

Pode investigar a fundo pra ver se faltou mais alguma coisa?

Obrigado!

**Comment by matheusgimenez** [comment]
Funcionando agora:

![captura de tela de 2016-03-07 19 16 24](https://cloud.githubusercontent.com/assets/4724804/13585211/343be41e-e499-11e5-9d9c-2f4a05e9f3c0.png)
![screenshot-brasawp art br 2016-03-07 19-15-07](https://cloud.githubusercontent.com/assets/4724804/13585212/350fbd98-e499-11e5-81be-3b0f72c47cd7.png)

**Comment by matheusgimenez** [comment]
Eram os dados da conta ftp que estavam errados

**Comment by LuwkasLima** [comment]
@matheusgimenez nos meus testes aqui encontrei 2 produtos que nao estao iguais ao arquivo. Vou explicar abaixo toda a analise que eu fiz pra ver se te ajuda a entender o que pode estar acontecendo:

1 - Eu fiu no Painel de COntrole e busquei a lista de produtos que aparecem como "Out of stock". Voce pode notar que o numero eh absurdamente alto no ambiente de dev:

![image](https://cloud.githubusercontent.com/assets/5949986/13684877/67240c80-e6d3-11e5-8385-d8bb43c40110.png)

2 - Um a um, fui copiando seus SKUs e olhando no arquivo que esta disponivel no servidor da DAMS:

Painel:
![image](https://cloud.githubusercontent.com/assets/5949986/13684906/8fc07ce6-e6d3-11e5-9b1d-ab5b0e86cdd1.png)

XML:
![image](https://cloud.githubusercontent.com/assets/5949986/13684918/9f72caf4-e6d3-11e5-988a-32f8bfc5b303.png)

SKU:
![image](https://cloud.githubusercontent.com/assets/5949986/13684935/af1050b2-e6d3-11e5-8144-2a7c33fbfbcf.png)

### Segundo Exemplo

Painel:
![image](https://cloud.githubusercontent.com/assets/5949986/13684949/c7bd4bc4-e6d3-11e5-8ed0-3779160f7e68.png)

XML:
![image](https://cloud.githubusercontent.com/assets/5949986/13684962/d2993cec-e6d3-11e5-9ef9-d5f8ec17c6df.png)

SKU: 
![image](https://cloud.githubusercontent.com/assets/5949986/13684971/e17215e0-e6d3-11e5-9667-a03577809630.png)

Precisamos ter certeza que a interface de estoque esta funcionando antes de promover tudo pra Producao. Eles ja estao reclamando da interface...=(

**Comment by LuwkasLima** [comment]
@matheusgimenez fiz o teste aqui. Ta aprovado hermano!!...obrigado!

**Comment by LuwkasLima** [comment]
@matheusgimenez Verificando em ambiente de Producao, achei alguns produtos que nao estao sendo atualizados pela interface. Alguns exemplos:

SKU: P83B

![image](https://cloud.githubusercontent.com/assets/5949986/13826005/54df82d4-eb83-11e5-812e-861cf6e78e2a.png)

Producao:
![image](https://cloud.githubusercontent.com/assets/5949986/13826027/69dc112a-eb83-11e5-8d96-cd212dd4e2cc.png)

SKU: P63O
![image](https://cloud.githubusercontent.com/assets/5949986/13826054/8f9ea314-eb83-11e5-99de-661f21aa07dc.png)

Producao: 

![image](https://cloud.githubusercontent.com/assets/5949986/13826321/d44198ea-eb84-11e5-9116-676c1034ec0c.png)

**Comment by LuwkasLima** [comment]
Esta funcionando perfeitamente em producao! Obrigado @matheusgimenez!!!
