### ISSUE TITLE
[URGENTE] - Pente Fino Mobile - Single de Produtos - Ordem das seções

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#159]
pra mim aparece na Single-Product:
1 - Header
2 - Categories
3 - Filters
4 - 2 Banners
5 - Storage
6 - Aí sim o produto com descrição, preço, foto. etc

É preciso rever esta lógica da ordem, o produto está ficando MUITO lá pra baixo e com coisas supérfluas na parte de cima.

**Comment by everaldomatias** [comment]
Solved in https://github.com/brasadesign/wp-docklands/commit/8eca822c6db0b43dcb492ecdd32be15cf4d74097
