### ISSUE TITLE
[URGENTE] - Pente Fino Mobile - Single de Produtos - Padronizar Add to Cart ou Enquire

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#160]
Na Single Product não aparece na página o ADICIONAR AO CARRINHO no próprio produtor. 

<img width="470" alt="captura de tela 2016-02-27 as 14 15 20" src="https://cloud.githubusercontent.com/assets/5107285/13374230/21e4a5c8-dd5d-11e5-9250-2722c90b1d4f.png">

**Comment by diogosp** [comment]
**obs: mesmo se escolhe as opções de cor etc. Só pra ficar claro.**

**Comment by diogosp** [comment]
@LuwkasLima aqui entendi um problema. o Site está com duas formas de ADD: Add to Enquire e Add to Cart em outros locais.
E fora que na Single Product este botão não tem destaque nenhum....

<img width="319" alt="captura de tela 2016-02-27 as 15 14 52" src="https://cloud.githubusercontent.com/assets/5107285/13374495/deafa3e0-dd64-11e5-9e3d-cbdd1158d8b6.png">

**Comment by everaldomatias** [comment]
@diogosp na single ele tem apenas esse botão de "Add to Enquire".

Se for mudar a nomenclatura do botão e melhorar o posicionamento dessa informação na single-product vou pedir a gentileza de assignarem a issue ao @matheusgimenez

**Comment by diogosp** [comment]
@everaldomatias Então deixa assim pro @LuwkasLima ver

**Comment by everaldomatias** [comment]
Ok

**Comment by everaldomatias** [comment]
@LuwkasLima ??

**Comment by everaldomatias** [comment]
@diogosp conversando com o @LuwkasLima a definição é a seguinte:

Add to Enquire -> Produtos para 'Cotação';
Add to Cart -> Produtos que serão vendidos diretamente pelo site.

**Comment by LuwkasLima** [comment]
@everaldomatias aqui vai algumas correcoes na SIingle Produto que precisam ser feitas:

1 - Todas as caracteristicas do produto estao misturadas em uma linha. Colocar elas em coluna:

![image](https://cloud.githubusercontent.com/assets/5949986/13685284/38476ed2-e6d5-11e5-94f6-2c02bf5d20c5.png)

2 - Dar um espaco entre a mensagem de "Adicionado ao Carrinho" e os botoes:

![image](https://cloud.githubusercontent.com/assets/5949986/13685297/512c8e46-e6d5-11e5-827e-15dc90f27c81.png)

**Comment by LuwkasLima** [comment]
OK
