### ISSUE TITLE
[IMPORTANTE] - Pente Fino - Página "Payment and Security" no menu dá erro

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#162]
Não sei até que ponto isto é um erro ou uma falha do site (se existe mesmo esta página).

No menu "Payment & Security" vai pra uma página inexistente.

**Comment by LuwkasLima** [comment]
@diogosp obrigado pela info. De fato ja tinha outra issue que tratava do assunto. Vou acompanhar por la!...obrigado!
