### ISSUE TITLE
[URGENTE] - Pente Fino Mobile - campos de formulário sem borda em várias páginas

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#163]
Na versão mobile, os campos de formulário (user/e-mail - password) aparecem sem borda. E fica confuso pro usuário pra clicar ali.

http://brasawp.art.br/docklands/my-account/

<img width="347" alt="captura de tela 2016-02-27 as 14 31 37" src="https://cloud.githubusercontent.com/assets/5107285/13374300/1403d4b8-dd5f-11e5-94a3-cf35d5fadabc.png">

**Comment by diogosp** [comment]
Na página "Enviar pra um amigo" tb não aparece borda.

<img width="315" alt="captura de tela 2016-02-27 as 14 36 00" src="https://cloud.githubusercontent.com/assets/5107285/13374309/848c22a8-dd5f-11e5-8e3b-ead1a463b99d.png">

**Comment by diogosp** [comment]
Na Página de Checkou os campos de preenchimento também aparecem sem Borda.

<img width="340" alt="captura de tela 2016-02-27 as 15 08 12" src="https://cloud.githubusercontent.com/assets/5107285/13374447/f63da328-dd63-11e5-9cd1-43e04cd9c204.png">

**Comment by everaldomatias** [comment]
@diogosp qual navegador vc está usando? Ou mobile?
Porque aqui no Google Chrome as bordas estão normais.

![image](https://cloud.githubusercontent.com/assets/1918474/13376807/47948e14-dda3-11e5-8be0-fc7129f6f537.png)

**Comment by diogosp** [comment]
@everaldomatias Usei Chrome. No Dev do desktop

**Comment by everaldomatias** [comment]
Eu também @diogosp 

![image](https://cloud.githubusercontent.com/assets/1918474/13376814/7cab944e-dda3-11e5-8b5c-119749e68722.png)

**Comment by diogosp** [comment]
@everaldomatias Eu tava selecionando modelos ali em cima. S4 e iPhone 6

**Comment by everaldomatias** [comment]
Eu também @diogosp 

![image](https://cloud.githubusercontent.com/assets/1918474/13382760/46d3b6e0-de5b-11e5-9fd1-8c0cd510be33.png)

@LuwkasLima veja como está para você por favor e qualquer coisa feche a issue.

**Comment by LuwkasLima** [comment]
Funcionou legal aqui no cell pelo Firefox. @diogosp quer checar novamente so pra termos certeza que esta ok? Testei o Login, Register, Billing e Order view

**Comment by diogosp** [comment]
@LuwkasLima Manda ver Lucas.
