### ISSUE TITLE
[URGENTE] - Pente Fino Mobile - Listagem de Categoria - definir melhor campo de produtos puxados

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#164]
Quando puxa uma categoria de produtos. Por exemplo **"Restaurante Chairs"** http://brasawp.art.br/docklands/product-category/cafe-and-restaurant/restaurant-chairs/

Na versão mobile não está muito claro a qual produto pertence os botões "Add to Cart" e "Details". Fica confuso se os botões são pro produto de cima ou de baixo.

<img width="346" alt="captura de tela 2016-02-27 as 14 42 57" src="https://cloud.githubusercontent.com/assets/5107285/13374353/f1e87bac-dd60-11e5-92c0-f047eba2928b.png">

**Comment by everaldomatias** [comment]
Solucionei aplicando um fundo em degrade e mais 'margin' entre os elementos.

![image](https://cloud.githubusercontent.com/assets/1918474/13382918/b0195bde-de5e-11e5-892a-37713b3e287a.png)
