### ISSUE TITLE
[URGENTE] Pagina de Services so aparece 10

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#167]
@matheusgimenez acho que essa parada aqui eh que faltou a paginacao:

Link: http://www.docklandsfurniture.com/services/

Existem 14 Services cadastrados, mas so aparecem 10 na lista.

**Comment by matheusgimenez** [comment]
@LuwkasLima Isso não ta previsto paginação, tem que exibir tudo

**Comment by LuwkasLima** [comment]
Beleza, obrigado por checar...

**Comment by LuwkasLima** [comment]
Ta beleza! Testado e aprovado!
