### ISSUE TITLE
[URGENTE] - Pente Fino Mobile - Checkout Page - rever ordem das seções

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#168]
Na página de checkout que deveria ser bem objetiva e clara pro cliente não fugir estão aparecendo uma série de seções antes da parte de preenchimento de dados pessoais e de pagamento

1 - Header
2 - Categories
3 - Destaques
4 - Aí sim Checkout.

<img width="342" alt="captura de tela 2016-02-27 as 15 09 25" src="https://cloud.githubusercontent.com/assets/5107285/13374465/5698c6da-dd64-11e5-8845-923600901a2e.png">

**Comment by everaldomatias** [comment]
Resolvido com simples display:none no #secondary. Mas isso precisa ser re-feito nas demais páginas com o item que o @matheusgimenez comentou.
