### ISSUE TITLE
[URGENTE] - Pente Fino Mobile - Pagina "Advanced Search"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#173]
@everaldomatias e @matheusgimenez existem 2 pontos que precisam ser corrigidos no Mobile da pagina "Advanced Search":

1 - Bread Crumb esta mal posicionado, veja imagem:
![image](https://cloud.githubusercontent.com/assets/5949986/13682427/5fdce3ea-e6c7-11e5-90ee-ea1282dd93cf.png)

2 - Assim que o usuario abre o Advanced Search, ele precisa ver de cara os Filtros e nao os produtos, faz sentido?

Alem disso, o Filtro atualmente esta mais "fino" do que o normal. Precizamos dar uma alargada..

![image](https://cloud.githubusercontent.com/assets/5949986/13682728/b9ca1cb4-e6c8-11e5-9afb-162372244521.png)

**Comment by everaldomatias** [comment]
@LuwkasLima só não consegui fazer a ordenação dos blocos aqui, para deixar os filtros antes dos produtos. @matheusgimenez ajuda nisso por favor?

**Comment by everaldomatias** [comment]
@LuwkasLima essa era uma que queria esclarecer com vc.

**Comment by LuwkasLima** [comment]
@everaldomatias  aqui precisamos de fato que apareca antes os filtros, se nao eh muito trabalho pra pessoa que quer buscar um produto em especifico ter que rolar a tela ateh la em baixo...

Isso pode te ajudar: http://stackoverflow.com/questions/12859045/switching-order-of-html-elements-when-layout-changes-in-responsive-web-design#12859860

**Comment by everaldomatias** [comment]
@LuwkasLima @LuwkasLima preciso da ajuda do @deshawn para isso...

**Comment by matheusgimenez** [comment]
Não usem jQuery pra isso.. existe um tipo de elemento novo no CSS chamado flexbox.

No caso, a div pai fica com display:flex; e a filha vc seta uma regra chamada order que vai receber um numero inteiro. Sacou?

Veja a documentação no FF:

https://developer.mozilla.org/en-US/docs/Web/CSS/order

**Comment by LuwkasLima** [comment]
@everaldomatias vi que voce nao mexeu nisso ainda, preciso que seja feito o quanto antes...

Adiciono aqui outro problieminha:

![image](https://cloud.githubusercontent.com/assets/5949986/15086690/1b7e16b6-13a8-11e6-86be-169a7db4aa6f.png)

**Comment by LuwkasLima** [comment]
@everaldomatias ficou muito bom o posicionamento de tudo!...

Voce nao conseguiu ordenar os blocos? Precisamos dos filtros antes...

**Comment by LuwkasLima** [comment]
@everaldomatias acho que nao ficou legal essa ordem, desculpe. Veja o que vc acha:

1- Filtro de Produtos
2- Lista de Produtos
3- Banners
4- Specials
5- Menu

Assim fica mais logico.

**Comment by everaldomatias** [comment]
Usei uma alternativa para poder funcionar a 're-order'. Removi os itens da direita do site (quando visto no desktop). Assim consegui organizar os itens da sidebar.

**Comment by LuwkasLima** [comment]
@everaldomatias muito boa a solucao cara! Prabens!!!...

Muito inteligente, boa sacada.

Manda Brasa!
