### ISSUE TITLE
[URGENTE] - Pente Fino Mobile - Carrinho de Compras

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#175]
@everaldomatias segue meus comentarios sobre a pagina "Cart"

1 - Aqui voce pode notar que os botoes estao cortando:

![image](https://cloud.githubusercontent.com/assets/5949986/13682913/97a847fe-e6c9-11e5-9a4e-f8fc934ec3da.png)

2 - Precisamos dar mais espaco pro nome do produto e pro preco aparecer corretamente. O Preco deve aparecer corretamente pra evitar problemas pra Docklands...

![image](https://cloud.githubusercontent.com/assets/5949986/13684153/0d3490d0-e6d0-11e5-9ddb-821ee4f9f11d.png)

4 - Existe um espaco GIGANTE em branco nessa pagina quando voce rola pra baixo:

![image](https://cloud.githubusercontent.com/assets/5949986/13684212/573c8dc2-e6d0-11e5-8b2d-e2598aafbbca.png)

**Comment by LuwkasLima** [comment]
@everaldomatias segue detalhes:

1 - Botoes ainda estao cortados:

![image](https://cloud.githubusercontent.com/assets/5949986/14000851/17d3e91e-f111-11e5-8c06-ea6d2259d44e.png)

2 - Ainda existe um espaco em branco enorme na pagina:

![image](https://cloud.githubusercontent.com/assets/5949986/14000873/36f33c0a-f111-11e5-9e97-34ad72f96134.png)

**Comment by everaldomatias** [comment]
@LuwkasLima quando puder me passe a resolução do seu celular por favor.

**Comment by LuwkasLima** [comment]
@everaldomatias ficou muito melhor, vlw! Mas precisamos deixa rum pouquinho mais fino, porque do jeito que esta fica muito ruim pro cliente ainda:

1 - Tenta dar um espaco entre o texto e as bordas da tabela de forma a deixar meio que com a mesma distancia em cima e em baixo.

2 - Estao aparecendo 2 botoes de Proceed to Checkout e ei acho que isso o @matheusgimenez deve saber mais...

![image](https://cloud.githubusercontent.com/assets/5949986/14328481/77d184a2-fbfc-11e5-9403-456b61bf2556.png)

3 - O texto do box ta cortando (tambem pode ser algo que o @matheusgimenez mexeu recentemente)
4 - O mesmo problema com os botoes do @isaquebrasileiro 2

![image](https://cloud.githubusercontent.com/assets/5949986/14328527/b5302e84-fbfc-11e5-8431-3cbcf08dfb6a.png)

**Comment by LuwkasLima** [comment]
@everaldomatias ficou muito bom cara, parabens!....ta fino agora!

No entanto, o ponto 2 ainda esta aberto:

2 - Estao aparecendo 2 botoes de Proceed to Checkout e ei acho que isso o @matheusgimenez deve saber mais...

![image](https://cloud.githubusercontent.com/assets/5949986/14575622/8e298406-0328-11e6-86d6-d31cfbe792ee.png)

**Comment by LuwkasLima** [comment]
Aprovado, podemos mandar pra producao!

**Comment by LuwkasLima** [comment]
@everaldomatias eu nao to fechando as issues porque eu deixo em status APROVADO ateh que a gente suba pra producao. Dai quando eu mando o e-mail pra cliente eu olho quais issues estao APROVADO e listo pra ela...

Dai eu venho e fecho...

**Comment by LuwkasLima** [comment]
@everaldomatias preciso de ajuda, ainda tem alguns pontos que precisamos atacar, vou detalha-los abaixo:

**1 - Advanced Search:**

Quando entramos pelo celular no Advanced Search, os produtos nao aparecem mais, somente o Menu (lembro que voce comentou algo do tipo, mas nao lembro a razao, pode me explicar?).

**2 - Lista de Produtos no Mobile:**

Os thumbnails de produtos ainda estao ruins, veja:

![image](https://cloud.githubusercontent.com/assets/5949986/20978007/e5c3fb08-bc6c-11e6-98da-6cf8b9164d85.png)

**3 - Paginacao do Advanced Search e lista de Produtos:**

Esta desalinhado os dois tipos de paginacao.

![image](https://cloud.githubusercontent.com/assets/5949986/20978131/5decb9da-bc6d-11e6-83b5-161ee49148bc.png)

**Comment by everaldomatias** [comment]
@LuwkasLima 
1 - Advanced Search.
Veja se agora está melhor.
Vale observar que tem bastante cache nesse servidor e pode demorar para vc conseguir visualizar. Sugiro limpar o cache antes de olhar.

**Comment by everaldomatias** [comment]
@LuwkasLima 
2 - Lista de Produtos no Mobile
Verifique por favor.
PS. Mesma orientação do cache.

**Comment by LuwkasLima** [comment]
@everaldomatias quase la mano, vmaos la...

1 - Os produtos estao perfeitos!

2 - Acho que voce sumiu com a paginacao, tem bem mais produtos no Advanced Search, mas agora nao aparece pagina, 1, 2, 3, etc...

![image](https://cloud.githubusercontent.com/assets/5949986/22125679/4197f128-de5a-11e6-8834-3ab7a5c0cc2b.png)

No Mobile ta a mesma coisa...

**Comment by LuwkasLima** [comment]
@everaldomatias @matheusgimenez @isaquemelo 

A Paginação do Advanced Search ainda não ta aparecendo. O @everaldomatias acha que tem a ver com o problema de atualizar os arquivos no servidor, mas as ultimas issues do @matheusgimenez e do @isaquemelo subiram normal.

Podem me ajudar a descobrir o que ta rolando? Não podemos subir pra produção com esse bug...

**Comment by LuwkasLima** [comment]
Observacao: Esse problema so aparece no BrasaWP. Nao esta em PRODUCAO, mas tenho medo de que isso ocorra se a gente subir a versao pra la...

**Comment by LuwkasLima** [comment]
Ja esta OK.
