### ISSUE TITLE
[IMPORTANTE] Twitter nao esta funcionando!

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#177]
Pessoal,

Depois da ultima versao que implementamos, o "widget" do Twitter nao esta funcionando nem em Producao e nem no ambiente de desenvolvimento. Ja fiz o teste (em ambos ambientes) modificando a conta para a conta da Brasa e a minha pessoal e nao funciona.

Pensei que pudesse ser incompatibilidade com o plugin W3 mas tbm nao eh...

![image](https://cloud.githubusercontent.com/assets/5949986/13829970/e293529a-eb97-11e5-87b7-05a44ef76f05.png)

**Comment by matheusgimenez** [comment]
Fixado no ultimo commit :)

Era a lib que uso que precisava atualizar.

**Comment by LuwkasLima** [comment]
@matheusgimenez nao esta funcionando no BrasaWP e nem em Producao (mudei a conta do twitter nos dois pra testar e limpei os caches...)

**Comment by LuwkasLima** [comment]
Ficou muito melhor assim! Muito bom @matheusgimenez
