### ISSUE TITLE
[IMPORTANTE] Remover "Not Found", Banner e Video da Pagina de Subcategorias

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#179]
@matheusgimenez existe uma pagina de subcategorias que vai ser usada pelo Docklands:

![image](https://cloud.githubusercontent.com/assets/5949986/13999407/32da2432-f10a-11e5-894c-92bf3834a50d.png)

Link: http://www.docklandsfurniture.com/product-category/desks/

Se voce rolar para baixo, vai ver que tem 2 coisas que nao deveriam aparecer nessa pagina:

![image](https://cloud.githubusercontent.com/assets/5949986/13999435/5548bce0-f10a-11e5-8060-97f11c8b836f.png)

2 - Alem disso, precisamos garantir uma paginacao pra cada 8 elementos:

![image](https://cloud.githubusercontent.com/assets/5949986/13999487/814b898a-f10a-11e5-926a-c1b0056d83c3.png)

**Comment by matheusgimenez** [comment]
Precisamos mesmo de páginação pra cada 8 elementos? Essas páginas não tem páginação por padrão, eu teria que criar um novo codigo pra isso e isso levaria mais algumas horinhas..

No mais, to resolvendo o bug do search

**Comment by matheusgimenez** [comment]
Resolvido o bug do search

**Comment by LuwkasLima** [comment]
@matheusgimenez imagino que essa pagina nao va ter muitos "quadrados" pra ter paginacao de fato. Pensei nisso porque em Producao os quadrados sao grandes (sabe dizer porque?):

Prod:
![selection_619](https://cloud.githubusercontent.com/assets/5949986/14400001/5a644cde-fdb8-11e5-983b-a9a2b6d658de.png)

Consegue dar um espacinho entre os quadrados pra ficar mais bonito?

![selection_618](https://cloud.githubusercontent.com/assets/5949986/14399989/3791c45c-fdb8-11e5-9e33-607755283eac.png)

Link: http://brasawp.art.br/docklands/product-category/desk/

**Comment by matheusgimenez** [comment]
Feito.

**Comment by LuwkasLima** [comment]
Perfect!
