### ISSUE TITLE
Breadcrumb 

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#18]
Matheus lembro de um breadcrumb para os produtos. Confirme se é apenas ali ou se é em todo site e programe issso por favor. 

Estou no celular e não consigo ver agora.

**Comment by matheusgimenez** [comment]
Removi o breadcrumb do woocommerce e adicionei o do Odin que funciona em todos post types.

**Comment by everaldomatias** [comment]
Ótimo.
