### ISSUE TITLE
[URGENTE] Opções de Produtos não aparecem no Dropbox

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#181]
@matheusgimenez tem algum bug que ta rolando em alguns produtos, que as opcoes nao ficam disponiveis pra serem escolhidas..

![image](https://cloud.githubusercontent.com/assets/5949986/14395019/e4525964-fd94-11e5-9630-ca4a6071a6dd.png)

Exemplo: http://www.docklandsfurniture.com/product/unison-four-multi-purpose-seating/

**Comment by matheusgimenez** [comment]
@LuwkasLima Nesse item especifico eu consegui resolver mas ainda não consigo explicar o que exatamente ta acontecendo, mas acho que o Google pode ajudar:

Temos dois tipos de atributos no woocommerce: taxonomias (que cria taxonomias pra cada atributo e cada item da aquele atributo se torna um termo) e existem os atributos simples, que ficam separados por |.

No caso ali, os dois primeiro são taxonomias, enquanto o ultimo (FRAME) é simples. Criei um novo atributo no painel e copiei cada variação pra ficar com o mesmo valor e funcionou. Não sei se isso é a solução em todos os casos, funcionou nesse e talvez o tio Google possa ajudar.

Para criar novos atributos, va no dashboard -> products -> Attributes (ultimo item).

**Comment by LuwkasLima** [comment]
@matheusgimenez mil desculpas por não ter visto isso com calma. Eu poderia ter identificado isso e não teria utilizado seu tempo. Vou me atentar a isso na próxima vez....

De qualquer forma muito obrigado, isso resolveu o problema!
