### ISSUE TITLE
Home > Nuvem de Tags

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#19]
@matheusgimenez aqui eles querem uma nuvem de tags.

A questão é se serão tags de posts ou produtos. Faça de uma forma que conseguimos alterar facilmente, mesmo no código.

![nuvem-de-tags](https://cloud.githubusercontent.com/assets/1918474/5988747/d97440a6-a954-11e4-8439-0e6e174db9ea.jpg)

**Comment by matheusgimenez** [comment]
Já tem essa opção no woocommerce.. só precisamos aplicar um sidebar ali e modificar o css se necessário

**Comment by everaldomatias** [comment]
Legal @matheusgimenez amanhã começa fazendo isso por favor.

**Comment by LuwkasLima** [comment]
@everaldomatias precisamos diminuir o tamanho da nuvem de tags aqui...
