### ISSUE TITLE
[Baixa Prioridade] Copiar Fotos da Galeria de Imagens

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#194]
@isaquemelo o pessoal da Docklands gostaria de fazer uma modificacao pra poder copiar as imagens da galeria dos produtos na Single de produtos. Pode me levantar quantas horas sao precisar pra esse trampo?

VLw!

**Comment by isaquemelo** [comment]
Mano em uma horinha ou menos faço isso..
.

**Comment by isaquemelo** [comment]
@LuwkasLima revisei e serão no mínimo duas horas

**Comment by LuwkasLima** [comment]
Como conversado com o Isaque, isso é parte do WooCommerce e portanto precisa ser feito como uma nova requisição.

**Comment by LuwkasLima** [comment]
Resolvido!
