### ISSUE TITLE
Borda das Imagens nos Posts e Paginas

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#197]
@isaquemelo voce chegou a mexer nisso pra me ajudar a tirar a borda cinza que estava estranha, mas acabou que passou um erro que eu nao vi pelo celular. Veja como fica a imagem:

![image](https://cloud.githubusercontent.com/assets/5949986/22123705/410e5a4c-de52-11e6-9a52-fb2d02ccac6b.png)

Link: http://www.docklandsfurniture.com/delivery-and-returns/cooling-off-period-e-commerce-only/

Se conseguir deixar sem borda ta otimo.

Obrigado!

**Comment by isaquemelo** [comment]
@LuwkasLima Já tinha corrigido isso.. Acho que algo sobrepôs o que eu fiz

**Comment by isaquemelo** [comment]
Feito.
![capturar](https://cloud.githubusercontent.com/assets/7103838/22126475/881cb81a-de76-11e6-8126-39fc377c5c52.PNG)

**Comment by isaquemelo** [comment]
![capturar](https://cloud.githubusercontent.com/assets/7103838/22303331/94e56638-e311-11e6-855f-17c7688c8f31.PNG)
Acho que agora foi @LuwkasLima rssrs

**Comment by LuwkasLima** [comment]
Agora vai!....ta ok, obrigado @isaquemelo !

**Comment by LuwkasLima** [comment]
Em Produção!
