### ISSUE TITLE
[Importante] Busca do Site nao apresenta todos os produtos

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#198]
@matheusgimenez temos mais um problema rolando com a busca. Se voce observar abaixo e fizer o teste em producao, vai ver que de fato, a busca do site (no header) nao encontra as palavras chave do titulo do produto. 

Palavra Chave: White Desk:

![image](https://cloud.githubusercontent.com/assets/5949986/22125305/c4fe2b42-de58-11e6-9812-31ca090ab984.png)

Link: http://www.docklandsfurniture.com/?post_type=product&s=White+Desk

Aparecem 2 opcoes na query.

Agora, se buscamos usando a busca do BLOG, encontramos outros produtos que possuem a palavra "White" e "Desk":

Observacao Importante: O plugin de Search by SKU esta DESABILITADO por mim.

![image](https://cloud.githubusercontent.com/assets/5949986/22125359/fbeab062-de58-11e6-8568-3c9fe0858e4b.png)

Link: http://www.docklandsfurniture.com/?s=White+Desk

**Comment by LuwkasLima** [comment]
Como conversado no chat, decobrimos que o plugin esta influenciando no resultaod a busca, que em vez de buscar por palavra chave, busca a palavra toda.

**Comment by LuwkasLima** [comment]
Search default do WP esta sendo utilizado e portanto busca as palavras separadas, trazendo resultados para cada uma das palavras buscadas.

*Nota: Vamos restringir a busca do NEWS para nao aparecer produtos, somente posts de News.

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
Em Produção!
