### ISSUE TITLE
[Prioridade Media] Ajustar Template Services para ficar igual Cases

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#199]
@matheusgimenez, eu achei que havia pedido isso pra voce, mas nao encontrei nenhuma issue com esse detalhe, entao peço desculpas por isso. Não é algo muito complexo, dê uma olhada:

Assim como você fez com a issue #183 precisamos aplicar o mesmo template da pagina CASES na pagina SERVICES:

Link: http://www.docklandsfurniture.com/cases/
![image](https://cloud.githubusercontent.com/assets/5949986/22126239/8acf0370-de5c-11e6-8bdd-788fc299cfa0.png)

Link: http://www.docklandsfurniture.com/services/
![image](https://cloud.githubusercontent.com/assets/5949986/22126248/9a45e350-de5c-11e6-9eeb-80bde588cba8.png)

Ou seja, queremos que as duas tenham a mesma cara.

**Comment by matheusgimenez** [comment]
Feito

**Comment by LuwkasLima** [comment]
Perfeito!...pode ir pra Prod!

**Comment by LuwkasLima** [comment]
Em produção!
