### ISSUE TITLE
Recentrly viewed items

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#2]
@matheusgimenez aqui vamos aproveitar a funcionalidade que criamos para o TechCD, e modificar um pouco para ela exibir uma lista dos 5 últimos itens visualizados pelo usuário.

O layout deixa que eu aplico, mas para você entender onde ele vai aparecer, segue um print:

![print-1](https://cloud.githubusercontent.com/assets/1918474/5700534/cc1dde18-9a26-11e4-9170-79af1564f568.jpg)

Ele vai aparecer nos archives e singles do WooCommerce.

**Comment by matheusgimenez** [comment]
Isso vai precisar ser outra coisa.. Pq vai ser os ultimos vistos pelo usuario certo?

Podemos usar o WP_Session:
https://github.com/ericmann/wp-session-manager
