### ISSUE TITLE
Não adiciona ao carrinho

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#20]
@matheusgimenez dá uma olhada nisso por favor, quando estou na single e clico em add to enquire ele exibe a seguinte mensagem:

![print-erro](https://cloud.githubusercontent.com/assets/1918474/6010877/76c4066a-ab1d-11e4-965c-52a14aa26f64.jpg)

E na home e outros archives onde aparecem aquele botão laranja de add to cart não funciona.

**Comment by matheusgimenez** [comment]
Você já viu se o produto está com estoque? Parece ser algum tipo de configuração do produto no woocommerce.. aqui funciona

**Comment by everaldomatias** [comment]
Conseguimos fechar essa issue?

**Comment by everaldomatias** [comment]
@matheusgimenez ?
