### ISSUE TITLE
[Importante] Product per Page na Busca

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#201]
Resumo: Logo apos fazer a busca de um produto usando o campo de Busca do Header, se tentamos mudar o numero de produtos apresentados na pagina de 12 para 24 ou 36, a busca eh resetada e aparecem TODOS os produtos.

Siga os passos:

1 - Faça uma busca por "chair":

![image](https://cloud.githubusercontent.com/assets/5949986/22312497/b72eb094-e31d-11e6-9066-e6f9db1ce24b.png)

2 - Va até o final da pagina e mude de 12 para 24 produtos por pagina:

![image](https://cloud.githubusercontent.com/assets/5949986/22312526/d5141edc-e31d-11e6-81df-8710fa9a5ab6.png)

3 - Veja o resultado: Voce vai ver que em vez de mostrar 24 cadeiras, agora mostra 24 produtos.

**Comment by matheusgimenez** [comment]
Já foi resolvido, esqueci de colocar pra revisão.

**Comment by LuwkasLima** [comment]
@matheusgimenez antes de fechar essa issue, precisamos entender porque quando fazemos a busca, ele deixa 2 espacos de produto vazio, veja:

![image](https://cloud.githubusercontent.com/assets/5949986/22487643/cb1805be-e7d3-11e6-99d1-a765d3c20900.png)

Eu achei que nao havia mais produtos, mas se vc clica pra mostrar mais 24 ou 36 por pagina, ele mostra mais produtos e nao aparece mais o espaco. Mas pra pessoa navegando, pode achar que nao tem mais produtos.

**Comment by LuwkasLima** [comment]
Oi @matheusgimenez, rolou uma coisa estranha...rs

No ambiente de DEV estou tendo esse problema aqui quando mudo de 12 pra 24 ou 36 per page:

![image](https://cloud.githubusercontent.com/assets/5949986/22488161/2b776ef2-e7d6-11e6-8c42-98eccd926c77.png)

No entanto, em PRODUCAO, esta funcionando...

Veja se vc esqueceu algo, ou se vc modificou algo que afetou o funcionamento no BrasaWP.

Vlw!

**Comment by LuwkasLima** [comment]
@matheusgimenez caminhamos com algo aqui?

**Comment by LuwkasLima** [comment]
@matheusgimenez o que eu temia aconteceu, depois que vc subiu as ultimas alteracoes, o problema agora acontece em PRODUCAO. Preciso que vc veja isso antes que a cliente veja...

![image](https://cloud.githubusercontent.com/assets/5949986/23149696/704492fc-f7b3-11e6-90f6-9821148e3c79.png)

**Comment by matheusgimenez** [comment]
Resolvido. Está no dev e em produção!

**Comment by LuwkasLima** [comment]
Perfeito! Fechando....

**Comment by LuwkasLima** [comment]
@matheusgimenez o mesmo problema relatado ali em cima, agora esta aparecendo em outra area do site. Siga os passos abaixo (em Producao):

1 - Menu: USED > USED OFFICE CHAIRS
![image](https://cloud.githubusercontent.com/assets/5949986/24049697/cff71652-0afa-11e7-8549-52fc4a608ed9.png)

2 - Selecione 36 ou 24 per page:
![image](https://cloud.githubusercontent.com/assets/5949986/24049743/f9b773ec-0afa-11e7-9fd7-de948de584e5.png)

3 - Veja que o filtro muda e apresenta TODOS os produtos:
![image](https://cloud.githubusercontent.com/assets/5949986/24049860/3115a8fe-0afb-11e7-9d35-14f717a32357.png)

Imagino que a solucao deva ser a mesma utilizada la em cima, so precisa atualizar em todas as paginas que possuem esse filtro.

**Comment by LuwkasLima** [comment]
@matheusgimenez ta funfando! Fechamos!
