### ISSUE TITLE
Bug quando clica em Add to Enquire

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#21]
Aqui está dando um erro quando clico em Add to Enquire ele abre essa área em branco no HTML:

![print-erro](https://cloud.githubusercontent.com/assets/1918474/6011037/ecefdb42-ab1e-11e4-87a7-18c4be84f992.jpg)

Mas quando clico novamente ele some. Parece até um toggle abrindo e fechando.

**Comment by matheusgimenez** [comment]
Estranho.. aqui não ta ocorrendo, precisa ver as configurações do produto, o que esse produto tem que os meus do ambiente de teste não tem.. ai consigo testar o erro aqui

**Comment by everaldomatias** [comment]
Conseguimos fechar essa issue?

**Comment by everaldomatias** [comment]
@matheusgimenez ?

**Comment by matheusgimenez** [comment]
Creio que sim
