### ISSUE TITLE
Taxa VAT

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#23]
Precisamos fazer esse item funcionar nos valores dos produtos. Isso está na administração? É setado em cada produto ou é geral?

**Comment by matheusgimenez** [comment]
Isso é setado no admin, da pra fazer por configuração geral ou na página de edição do produto. Sendo que a segunda anula a primeira

**Comment by everaldomatias** [comment]
Deixa setado lá em 20% por favor?

**Comment by matheusgimenez** [comment]
Calma ai.. to fazendo o issue da página contato.. se não me perco aqui hehe

**Comment by everaldomatias** [comment]
Essa fechou?

**Comment by matheusgimenez** [comment]
Sim

**Comment by everaldomatias** [comment]
@matheusgimenez reabrindo essa issue porque eles tiveram um entendimento sobre essa taxa agora.

Ela precisa ser calculada no carrinho também, antes da finalização, e esses 20% deve ser cobrado em cima de tudo Produto + Entrega \* VAT.

Você acha que o flow do carrinho já permite isso?

**Comment by matheusgimenez** [comment]
Me perdi agora, a taxa não vai ser automatica mais?

**Comment by everaldomatias** [comment]
Vai sim. Mas ela precisa ser cobrada sobre o valor final, ou seja, incluindo a entrega.

E isso só dá para fazer no carrinho, certo. Então nos preços podemos deixar como está, mas a demanda agora é conseguir ver ao finalizar ao calcular o frete ele calculando 20% em cima de tudo.

**Comment by matheusgimenez** [comment]
É, não sei como fazer isso no woocommerce :(

**Comment by everaldomatias** [comment]
Pessoal @willowmagrini @diegorojas podem tentar nos ajudar?

Precisamos aplicar um valor de 20% sobre a venda, e isso inclui o frete e o produto. Ou seja, ele vai calculando o preço e quando faz a cotação do frete, no valor total é adicionado essa taxa VAT de 20%.

**Comment by matheusgimenez** [comment]
Acho que o woocommerce já tem essa opção por padrão, pelo menos achei algo, testa dps no brasawp que ta setado lá :)

**Comment by everaldomatias** [comment]
Legal...
