### ISSUE TITLE
[Prioridade Media] Produtos indisponíveis com frase de apoio.

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#24]
O Woo já oferece a possibilidade de exibir o produto e 'indisponibiliza-lo', com isso o Cliente tem a demanda de adicionar uma mensagem convidando a pessoa a conversar no chat (vamos adicionar plugin).

**Comment by LuwkasLima** [comment]
@everaldomatias precisa ver o que precisa ser feito aqui...

**Comment by LuwkasLima** [comment]
Nao sei o que eh isso e a cliente tbm nao comentou...
