### ISSUE TITLE
Usuário vendedores

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#25]
Criar um perfil para vendedores poderem reduzir a quantidade de itens no estoque. Teria como restringir a tal ponto? O Woo oferece cap para campos do CPT?

**Comment by matheusgimenez** [comment]
Dificil hein hehe..

O maximo que eu poderia fazer era um role de vendedor onde ele só poderia atualizar posts, não adicionar novos...

**Comment by everaldomatias** [comment]
Entendi, é uma opção, mas vamos tentar eliminar outras possibilidades, pensei também em algo assim, se liga:

![print-1](https://cloud.githubusercontent.com/assets/1918474/6146957/9dd2a5aa-b1d9-11e4-99f6-d1f78fd9b574.jpg)

Ai, ao clicar no 'lápis' ele abre um modal para editar status e quantidade, (abaixo ideia e não layout):

![print-2](https://cloud.githubusercontent.com/assets/1918474/6146966/bad5df46-b1d9-11e4-8327-332ecc839d5d.jpg)

E para esse usuário, 'vendedor', deixamos apenas a role para essa página e não para entrar na edit.php.

O que acha @matheusgimenez?

**Comment by matheusgimenez** [comment]
boa ideia.. vou fazer isso

**Comment by everaldomatias** [comment]
Legal @matheusgimenez manda Brasa nisso ai, depois vou relatar mais coisas da reunião, mas por hora esse é o mais complexo.

Se for complicado fazer isso no backend, podemos deixar no front (não sei se será mais fácil).

Mas a idéia do usuário 'vendedor' é que ele tenha acesso apenas a isso, seu perfil e a um plugin de chat que vamos aplicar.

**Comment by everaldomatias** [comment]
Mano, ficou animal. Depois faço um CSS ali na administração do modal.

Uma pergunta, teria como depois de clicar em 'Save' ele fechar o modal, recarregar a página? Pois assim ele já visualiza o item alterado.

**Comment by everaldomatias** [comment]
@matheusgimenez uma pergunta, teria como depois de clicar em 'Save' ele fechar o modal, recarregar a página? Pois assim ele já visualiza o item alterado.

**Comment by everaldomatias** [comment]
@matheusgimenez ?

**Comment by matheusgimenez** [comment]
Beleza, vou fazer :)
