### ISSUE TITLE
Conflito Options (Manter Options do Odin)

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#26]
@matheusgimenez acho que tivemos um conflito entre o Options do Odin e do ACF.

Acho melhor mantermos o do Odin, para isso temos que migrar todos os campos que já estão criados em /wp-admin/themes.php?page=odin-options para o Odin.

Você faz isso, por favor?

**Comment by matheusgimenez** [comment]
Tem algum campo que não ta no odin? Pq não lembro de ter criado algo fora dele

**Comment by everaldomatias** [comment]
Acho que aquelas informações do Twitter nao estão no ACF mas estão em um theme options dentro de aparência.

**Comment by matheusgimenez** [comment]
Eu me perdi cara.. mas ele já está no odin, vc ta falando para deixar de usar o odin e passar pro acf, isso?

**Comment by matheusgimenez** [comment]
Se for leia sua explicação acima pq ta tudo enrolado heheuehe

**Comment by everaldomatias** [comment]
Deixa eu tentar melhorar.

Segue o titulo da Issue. Manter Odin, mas para isso temoa que copiar os fields que ja criamos no ACF.

Depois disso desativamos o Optins ACF e não ele todo.

**Comment by matheusgimenez** [comment]
Eve, pra isso preciso que você jogue pro PHP esses campos, ai eu passo eles pro Odin, do contrário não tenho como saber quais campos são o que :(

**Comment by everaldomatias** [comment]
Tá lá @matheusgimenez https://github.com/brasadesign/wp-docklands/commit/a889f9c25a71944e4a075edf38488b7d7854e5ab branch 'options'

**Comment by everaldomatias** [comment]
@matheusgimenez para fecharmos essa issue, chama no tema as informações, por favor.

**Comment by matheusgimenez** [comment]
Não entendi eve

**Comment by matheusgimenez** [comment]
Ops, cliquei errado na hora de enviar e acabei fechando.. sorry for that hehe

**Comment by everaldomatias** [comment]
Fazer o echo $options['exemplo_field'] nos devidos lugares

**Comment by matheusgimenez** [comment]
já ta

**Comment by everaldomatias** [comment]
Fechando então ;)
