### ISSUE TITLE
Advanced Search - Loop de últimos produtos na primeira página

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#28]
Acesse o brasawp.../docklands/advanced-search/ você vai ver a página inicial do Advanced Search. É um template page, precisamos adicionar um query inicial para o cara não cair em uma página em branco, seguindo esse layout: 
![advanced_search](https://cloud.githubusercontent.com/assets/1918474/6380823/356476b8-bd1b-11e4-86f1-b5274b3c1173.jpg)

Esse é o mesmo layout do resultado da busca. Veja ai se é mais fácil fazer de outra forma que não seja com Template Page.

**Comment by matheusgimenez** [comment]
Hm.. me enrolei.. o advanced search é ta funcionando junto com o search default do wp.. precisa ser em página separada?

**Comment by everaldomatias** [comment]
Foi isso que conversamos no Telegram Matheus?

**Comment by everaldomatias** [comment]
@matheusgimenez essa não consegui ver, veja: http://brasawp.art.br/docklands/advanced-search/

Tem que fazer alguma configuração/comando diferente?

**Comment by everaldomatias** [comment]
@matheusgimenez ?

**Comment by matheusgimenez** [comment]
Bizarro.. funciona aqui '-'

**Comment by everaldomatias** [comment]
Vou tentar fazer mais alguns testes e mandar o tema todo para produção. Depoia volto aqui.
