### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#3]
@matheusgimenez para os produtos do WooCommerce, vamos precisar de uma buscar com filtros, veja o layout:
![advanced_search](https://cloud.githubusercontent.com/assets/1918474/5700570/619b26d0-9a27-11e4-9149-f4c194f4d193.jpg)
A sidebar possui as possibilidades de filtros. Dê uma olhada e em caso de dúvida vamos nos falando por aqui ou Telegram.

Vale ressaltar que além das categorias de produtos, eles vão ter uma separação dos produtos em Novos / Usados / Aluguel. Vamos precisar avaliar se criamos uma nova taxonomia para isso, porque isso será uma grande divisão dos produtos.

**Comment by matheusgimenez** [comment]
Eve.. tenho algumas dúvidas quanto a isso.. a primeira é onde fica o input de texto do search?

Segundo: existe a possibilidade da aquele input de preço maximo ser um taxonomy? Facilitaria muito as coisas, rs

**Comment by matheusgimenez** [comment]
Eve.. preciso entender melhor o que vai ser o que ai, ok?

**Comment by everaldomatias** [comment]
Pelo layout ele não apresenta o input de texto. Vou procurar um site de exemplo aqui e te mando.

Sobre o taxonomy, pode ser sim, mas conseguimos fazer com que o WP marque ela automaticamente, ou seja, se o cara setou o valor em 25, o WP entende e adiciona a taxonomy "de 0 a 50". Entendeu?

**Comment by matheusgimenez** [comment]
Ok

**Comment by everaldomatias** [comment]
@matheusgimenez vi que aplicou lá no BrasaWP, obrigado.

O archive, resultado disso já está programado?

**Comment by matheusgimenez** [comment]
Vou terminar amanhã de manhã provavelmente.. ele é basicamente o mesmo archive do woo

**Comment by everaldomatias** [comment]
Beleza.
