### ISSUE TITLE
Entrega do Produtos (Delivery)

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#34]
@LuwkasLima @diegorojas @willowmagrini @matheusgimenez 
Pessoal na última renião que tive com o cliente ele trouxe uma demanda que gostaria de compartilhar com todos para conseguirmos chegar em uma solução simplificada e útil dentro do Woo.

Eles tem valores diferentes para cada 'setor' da cidade, como podemos gerenciar isso no Woo?
Eles nos envaram um excel com os valores, são aproximadamente 100 valores.

**Comment by matheusgimenez** [comment]
O woocommerce tem um sistema que cria essa variação via CEP, mas nunca usei :(

**Comment by everaldomatias** [comment]
Opa, ai melhorou a conversa.
Você consegue dar uma olhada nisso @matheusgimenez?

Lembrando que eles estão em Londres:

Hackney Road
London, United Kingdom

**Comment by everaldomatias** [comment]
@matheusgimenez conseguiu ver algo disso?
@willowmagrini @diegorojas alguma ideia?

**Comment by matheusgimenez** [comment]
Achei um plugin que faz isso:

https://wordpress.org/plugins/postcode-shipping/ 

Pelo que testei funciona, só precisa ir criando as variações de CEP

**Comment by everaldomatias** [comment]
@matheusgimenez vamos precisar retomar isso.

**Comment by everaldomatias** [comment]
Será que não temos algum hook no checkout onde possamos adicionar um select com esses valores e ele adicionar ao valor total?

**Comment by matheusgimenez** [comment]
Vou tentar algo assim

**Comment by everaldomatias** [comment]
Legal.

**Comment by LuwkasLima** [comment]
O cara entao vai colocar o postcode que pode ser o grande:
User: WC2H 7JJ

A logica vai buscar na base por precos na seguinte ordem:
1 - WC2H 7JJ
2 - WC2H 7J
3 - WC2H 7
4 - WC2H
5 - WC2
6 - WC

Se encontrar o valor na base, retorna o valor e coloca na variavel referente ao Frete.

Detalhes da logica de criacao dos Postcodes podem ser encontrados aqui (Secao "Formatting"):
http://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom

**Comment by everaldomatias** [comment]
Obrigado equipe Brasa.
Vou fechar essa issue, mas qualquer bug podemos abrí-la novamente.
