### ISSUE TITLE
Adicionar campo no Options

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#35]
![print-docklands-3](https://cloud.githubusercontent.com/assets/1918474/7207240/4e24e7da-e50e-11e4-9a19-049e25e0013b.jpg)

**Comment by everaldomatias** [comment]
@matheusgimenez como suspeitamos, coloca isso no Options mesmo, para ela ter a maleabilidade de colocar a frase que desejar.

E então vamos adicionar um field nos produtos para ela especificar as mensagens específicas.

Pode fazer essa parte funcional que eu aplico no layout.

**Comment by matheusgimenez** [comment]
Não entendi.. vai ter um field no options e o outro no produto?

**Comment by everaldomatias** [comment]
Sim Matheus. O do options é para mudar o que aparece no print.

O do produto só registra ele (um field) que eu aplico no layout, na single de cada produto.

**Comment by everaldomatias** [comment]
Rolou?

Manda o que fez hoje para o git por favor.

**Comment by matheusgimenez** [comment]
Vish mano, deixei passar essa, fiquei a tarde inteira vendo o bug fantasma que ta rolando no spartanas, sorry :(

**Comment by matheusgimenez** [comment]
feito no ultimo issue - o nome do campo no banco pra recuperar é woo_shipping_content
