### ISSUE TITLE
Remover campo Key

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#37]
@matheusgimenez vamos remover esse campo Key.

Eu entendi para que ele serve e vou solucionar com uma funcionalidade do próprio Woo.

![docklands](https://cloud.githubusercontent.com/assets/1918474/7278222/649a9818-e8ea-11e4-9354-e84c1e7205f3.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
