### ISSUE TITLE
Widget Categories

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#4]
@matheusgimenez segue o print do widget que vamos criar para as categorias. Se o Woo já tiver, aplique o toggle para ele funcionar de acordo com o esperado pelo cliente.

![widget-categories](https://cloud.githubusercontent.com/assets/1918474/5778232/ed4438be-9d80-11e4-8576-591ebd7c6aca.jpg)

**Comment by matheusgimenez** [comment]
Feito no ultimo commit do branch taxs

**Comment by everaldomatias** [comment]
@matheusgimenez me diga por favor onde vejo o HTML disso para eu aplicar o estilo?

**Comment by matheusgimenez** [comment]
Não entendi sua dúvida Eve.

É só adicionar o widget de categorias do Woo e aplicar o CSS.

**Comment by everaldomatias** [comment]
Respondeu hehe é isso mesmo. Valew.
