### ISSUE TITLE
Header >> infos Contato

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#47]
@matheusgimenez aplica isso de acordo com o layout no header por favor.
Coloca o telefone como options na administração. O "email us", vamos aplicar o plugin 'Tidio Chat", aquele que estávamos usando na Brasa. E quando ele clicar nessa imagem, abrir aquela aba do plugin, OK?

![issue](https://cloud.githubusercontent.com/assets/1918474/7917969/8a1a4cb6-0864-11e5-9655-95a1ef481a31.gif)

**Comment by matheusgimenez** [comment]
Beleza. Fazendo
