### ISSUE TITLE
Ajustes Loop do Blog

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#50]
Ainda no blog, preciso que veja esses dois elementos no loop do blog, o link para compartilhar os posts nas redes sociais e o link Continue lendo.

![print](https://cloud.githubusercontent.com/assets/1918474/8180349/6929f408-13f3-11e5-9cad-891e058fe6b3.jpg)

Segue uma referência de como add isso sem plugin: http://crunchify.com/how-to-create-social-sharing-button-without-any-plugin-and-script-loading-wordpress-speed-optimization-goal/

**Comment by everaldomatias** [comment]
Aplica na produção por favor @matheusgimenez ?

**Comment by matheusgimenez** [comment]
adicionei o texto de continue reading e paginacao ja funcionando.. vou fechar aqui.

**Comment by matheusgimenez** [comment]
funcionando e fechando aqui
