### ISSUE TITLE
Paginação e Filtro no Blog

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#51]
@matheusgimenez conseguimos fazer essa filtragem? Para o visitante selecionar se quer ver 12, 24 ou 36 posts?

![print](https://cloud.githubusercontent.com/assets/1918474/8180422/ff1557b4-13f3-11e5-904b-8414f1032d15.jpg)

**Comment by everaldomatias** [comment]
Essa fechou @matheusgimenez ? Quando terminanr, mada para produção por favor?

**Comment by everaldomatias** [comment]
Essa fechou @matheusgimenez ? Quando terminanr, mada para produção por favor?

**Comment by LuwkasLima** [comment]
@everaldomatias acredito que nao implementamos isso aqui ainda certo?

**Comment by everaldomatias** [comment]
Acreido que não @LuwkasLima

**Comment by LuwkasLima** [comment]
@matheusgimenez isso tem a ver com a paginacao que vc arrumou hoje?

**Comment by matheusgimenez** [comment]
Não.. mas isso eu acho que eu já implementei antes

**Comment by LuwkasLima** [comment]
Consegue verificar pra mim? Eu estou limpando as issues pra ficar claro o tamanho da buxa ateh o fim da semana...

**Comment by matheusgimenez** [comment]
funcionando e fechando aqui
