### ISSUE TITLE
Cores dos Produtos

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#52]
@matheusgimenez essa issue é apenas para entender como configurar o lance das cores de cada produto. Consegui adicionar uma imagem lá ao criar o termo, mas quando vou criar um novo produto ele não exibe a imagem. Qual a mágica?

**Comment by everaldomatias** [comment]
@matheusgimenez veja se esse plugin funciona na single produtos: https://wordpress.org/plugins/taxonomy-images/

**Comment by matheusgimenez** [comment]
Single que vc fala é pagina de edição né?

**Comment by everaldomatias** [comment]
Na verdade se aparecer na single no frontend já resolve, na administração ela topa editar apenas pelo nome saca!? Tipo Blue, Yellow...
