### ISSUE TITLE
Filtros para Produtos - Ocultar Opcoes com ZERO "0" e Aplicar CSS

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#58]
Pessoal,

Precisamos aplicar 2 mudancas nos Filtros:

1 - Ocultar opcoes que estiverem com ZERO produtos como as que estao marcadas em vermelho no exemplo abaixo:

![image](https://cloud.githubusercontent.com/assets/5949986/10419442/d8e66f14-703d-11e5-9ccd-8cd66388c5e5.png)

2 - Aplicar folha de estilo para que os filtros atuais estejam como requisitado no layout enviado pela cliente:

![image](https://cloud.githubusercontent.com/assets/5949986/10419445/e792170c-703d-11e5-9e28-f3b2405895f2.png)

**Comment by LuwkasLima** [comment]
@everaldomatias o @matheusgimenez ja resolveu o esquema de ocultar as opcoes e os warnings que estavam aparecendo. Agora eh contigo no CSS pra deixar igual ao Layout:

![image](https://cloud.githubusercontent.com/assets/5949986/10464391/30d37420-71af-11e5-92d3-c537cdedf1f6.png)

Pra ajudar voce, lembre-se que isso ja foi feito antes, os filtros que tinhamos antes criados pelo Matheus ja tem o mesmo estilo...

**Comment by matheusgimenez** [comment]
@LuwkasLima só uma coisa quanto a esse issue.. o eve só precisa aplicar o css deles aparecendo e com o icone de mais + pra exibir todos.. dps faço por JS o esquema de toggle..

**Comment by LuwkasLima** [comment]
Belo trabalho @everaldomatias e @matheusgimenez !

**Comment by everaldomatias** [comment]
Valew @LuwkasLima e @matheusgimenez
