### ISSUE TITLE
Carrinho de Compras - "Add to cart" nao funciona

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#60]
Oi Pessoal,

Acabo de fazer um teste de adicionar um produto atraves do botao "add to cart" mas nao esta adicionando ao carriho:

![image](https://cloud.githubusercontent.com/assets/5949986/10436338/637f84dc-70eb-11e5-8c7e-baf1c95d4d1e.png)

**Comment by LuwkasLima** [comment]
Acho que descobri porque...rs

![image](https://cloud.githubusercontent.com/assets/5949986/10436370/914edb74-70eb-11e5-9447-c36d9a92878a.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez eu achei que era uma coisa, mas nao eh...a mensagem ainda aparece quando tento usar o botao do lado de fora. Eh como se ele nao soubesse que tem que usar o SKU default pra colocar no carrinho..

**Comment by LuwkasLima** [comment]
@matheusgimenez nao consegui resolver esse. Se voce puder investigar o que acontece eu agradeco...

**Comment by LuwkasLima** [comment]
@matheusgimenez segue um exemplo:

http://brasawp.art.br/docklands/product/system-combination-bookcase-with-horizontal-tambour-secondary-storage/

O produto possui um SKU default como voce pode ver aqui:

![image](https://cloud.githubusercontent.com/assets/5949986/10979040/c8e40046-83bf-11e5-9ee2-2ed3e3e71811.png)

![image](https://cloud.githubusercontent.com/assets/5949986/10979078/fbc4133e-83bf-11e5-9e23-ccd400f7e543.png)

No entanto, se voce clica no Botao "Add to Cart" na Home Page, ele nao adiciona o produto no carrinho:

![image](https://cloud.githubusercontent.com/assets/5949986/10979114/35682238-83c0-11e5-86b0-82db47282b5d.png)

![image](https://cloud.githubusercontent.com/assets/5949986/10979121/40932126-83c0-11e5-8f5e-a2ab36811dbe.png)

Uma coisa curiosa eh que se voce entra no single do produto e clica em "Add to Enquire", funciona tranquilamente:

![image](https://cloud.githubusercontent.com/assets/5949986/10979147/7118f208-83c0-11e5-9ee7-e5db337f5aa9.png)

![image](https://cloud.githubusercontent.com/assets/5949986/10979159/838094be-83c0-11e5-88ba-b9d5dd02b9e6.png)

**Comment by matheusgimenez** [comment]
feito.. dps testa e diz se ta ok! :)

**Comment by LuwkasLima** [comment]
Perfeito!
