### ISSUE TITLE
Filtro de Produtos - Botao "Reset" nao funciona

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#61]
Oi pessoal,

Fazendo um teste aqui rapido do filtro no Advanced Search, percebi que o botao RESET nao funciona:

Link: http://brasawp.art.br/docklands/shop/?swoof=1&product_condition=used&pa_colour=white

![image](https://cloud.githubusercontent.com/assets/5949986/10458188/31af72d8-718f-11e5-9942-cccb49eaf62b.png)

**Comment by matheusgimenez** [comment]
feito no repo do plugin

**Comment by LuwkasLima** [comment]
@matheusgimenez eu achei uma paradinha estranha:

Quando abro o Advanced Search, ele me leva pra pagina: http://brasawp.art.br/docklands/advanced-search/

Dai se eu faco um filtro e depois clico em RESET ele me joga pra pagina: http://brasawp.art.br/docklands/shop/

Com um resultado diferente do da pagina Advanced Search.

**Comment by matheusgimenez** [comment]
@LuwkasLima isso acontece pq só fiz o botão redirecionar pra pagina de shop mesmo

**Comment by LuwkasLima** [comment]
@matheusgimenez funcionou legal. so existe um cenario onde temos um pequeno bug. Segue detalhes de como replciar:

1 - Escolha uma categoria:

![image](https://cloud.githubusercontent.com/assets/5949986/11004552/9a47f2c8-847e-11e5-91af-625097efb9cc.png)

2 - Filtrar por preço:

![image](https://cloud.githubusercontent.com/assets/5949986/11004563/ad86a78a-847e-11e5-9485-c4947c5c1c9a.png)

3 - Aplicar outro filtro qualquer:

![image](https://cloud.githubusercontent.com/assets/5949986/11004595/c9a5d5ee-847e-11e5-8a1f-9a2584c6869f.png)

4 - Dai voce clica em RESET e o resultado eh este:

![image](https://cloud.githubusercontent.com/assets/5949986/11004813/08ec11d6-8480-11e5-8f5f-2944888e0a5a.png)

Obs.: Percebi que apos fazer o filtro de preço, as categorias dos filtros abaixo nao atualizam, portanto, se voce clicar em uma das categorias, mas esta nao eh parte de nenhum dos produtos atualmente apresentados na lista (apos o filtro de preco) o resultado eh uma pagina em branco.

**Comment by LuwkasLima** [comment]
OK!
