### ISSUE TITLE
Add class in £

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#63]
@matheusgimenez precisamos que o elemento '£' nos archives tenham uma classe para conseguirmos aplicar um css e deixá-lo um pouco menor em relação ao preço.

Veja no print como está no WP e como deve ficar no Layout.

Pode ser algo no PHP ou por JS, não tem problema.

![print-issue](https://cloud.githubusercontent.com/assets/1918474/10726684/691328ec-7bbb-11e5-819b-dea523713954.jpg)

**Comment by LuwkasLima** [comment]
@matheusgimenez rolou essa parada aqui voce sabe?

**Comment by matheusgimenez** [comment]
classe adicionada e simbolo diminuido
