### ISSUE TITLE
Breadcrumb em cada template (e não no header.php)

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#64]
@matheusgimenez e @LuwkasLima estou mudando o Breadcrumb de lugar para ficar igual ao layout.

Antes ele estava dentro do header.php, mas como ele precisa aparecer ao lado direito (e não acima) da sidebar, ele agora vai ficar em todos os templates.

Peço a gentileza de que ao navegar no site e identificar a ausência do Breadcrumb, me avisem por favor.

![print-issue](https://cloud.githubusercontent.com/assets/1918474/10727155/c560e8ca-7bbe-11e5-848b-b198218b1eae.jpg)

**Comment by LuwkasLima** [comment]
@everaldomatias vc chegou a terminar? Eu nao vi os breadcrumbs... =(

**Comment by everaldomatias** [comment]
@LuwkasLima apliquei em várias áreas e conforme vou navegando e não encontro, coloco.
Se puder ajudar mandando print de onde falta, agilizaremos.

Valew.

**Comment by LuwkasLima** [comment]
@everaldomatias precisamos tambem colocar nos archives de uma determinada sub-categoria:

![image](https://cloud.githubusercontent.com/assets/5949986/11428186/4bf04dea-942e-11e5-8fca-2a7f5174b30f.png)

**Comment by LuwkasLima** [comment]
@everaldomatias lembrei de uma coisa tbm. O link da pagina "Products" precisa ir pro Advanced Search e nao pro "Shop":

![image](https://cloud.githubusercontent.com/assets/5949986/11429682/de194782-9440-11e5-8af3-dcfa868868cb.png)

**Comment by everaldomatias** [comment]
@matheusgimenez você pode ver se tem algum filtro para trocar po link de um dos itens do breadcrumb?

Precisamos que o link "Products" leve para o Advanced Search.

**Comment by matheusgimenez** [comment]
Consegui trocando na configuração do Woocommerce a página de shopping. Acho que fica mais fácil assim. 

Fiz em produção.. testa lá

**Comment by LuwkasLima** [comment]
@matheusgimenez legal mano, nao sabia que tinha essa opcao!...FECHADO!
