### ISSUE TITLE
Area de Produtos Relacionados

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#65]
@everaldomatias precisamos checar se a cliente pediu em algum momento uma area com produtos relacionados ou venda casada. Segundo ela, existem produtos que precisam aparecer em uma area de produtos relacionada, mas eu nao vi isso em nenhum produto e nao sei se implementamos.

Pode checar pra mim por gentileza?

**Comment by everaldomatias** [comment]
![used new4_product_page](https://cloud.githubusercontent.com/assets/1918474/10745562/2664886e-7c2a-11e5-9b47-d9cfa1aec939.jpg)

**Comment by LuwkasLima** [comment]
Eh isso mesmo @everaldomatias !

Precisamos ver se isso foi desenvolvido, ou se vamos ter que correr com isso tbm. Consegue validar no tema?

![image](https://cloud.githubusercontent.com/assets/5949986/10746150/01044ed8-7c16-11e5-9d49-2c10a01113fa.png)

**Comment by everaldomatias** [comment]
@LuwkasLima aqui temos uma questão, Produtos Relacionados temos algo pronto no Woo que são os Up Sells, mas pelo layout me parece que ela quer listar categorias (Storages, Chairs, Desks), faz sentido? Desenvolvemos dessa forma que ela propõe?

**Comment by LuwkasLima** [comment]
@everaldomatias enviei pra ela a pergunta, mas acho que vem bucha ai. Acho que comemos bola no comeco do desenvolvimento e eles devam pedir pra que quando clique em uma das opcao, ele te leve pra um Archive de produtos relacionados saca? E isso me parece bem grande cara...

Se voce puder buscar o historico de conversas do projeto pra ver se tem algum documento explicando isso ajudaria...

**Comment by everaldomatias** [comment]
@LuwkasLima apliquei o CSS, veja o exemplo: http://brasawp.art.br/docklands/product/wave-desk-maestro-25-sl/

Precisamos que o @matheusgimenez adicione agora um slider e faça com que o query do arquivo docklands-theme\woocommerce\single-product\up-sells.php seja a partir das categorias do produto. Hoje esse query é usado a partir dos UpSells setados no admin, mas sendo pelas categorias podemos separar isso e ser um query independente de config no admin.

**Comment by LuwkasLima** [comment]
@everaldomatias e @matheusgimenez deixem esse como esta. Aparentemente a cliente gostou de como esta aparecendo, entao vou deixar a issue aberta ateh validar...

**Comment by everaldomatias** [comment]
Movendo isso para: #83
