### ISSUE TITLE
[URGENTE] Novas Taxonomias - Ate dia 30/10

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#66]
Precisamos criar mais algumas taxonomias para serem usadas omo filtros. Elas sao as seguintes:

Door:
- Single Door
- 2 Door
- 3 or more doors

Drawers/Shelves:
- 2 drawers/shelves
- 3 drawers/shelves
- 4 drawers/shelves
- Multi drawers/shelves

Format:
- Straight Desks
- Wave Desks
- Executive Desks
- Bench Desks
- Height Adjustable Desks
- Home Office Desks
- Corner Desks
- Reproduction Desks
- Ergonomic
- Fixed Pedestal

Adjustaments:
- Fully 
- Arms
- No arms
- Height Adjustable
- Back Adjustable
- Lumbar support
- Fully ergonomic

**Comment by matheusgimenez** [comment]
adicionado no ultimo commit

**Comment by LuwkasLima** [comment]
Lindo!...

Vou checar e se tiver tudo OK fecho essa budega...

Obrigado!

2015-10-28 8:02 GMT-05:00 Matheus Gimenez Petroni notifications@github.com
:

> adicionado no ultimo commit
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brasadesign/wp-docklands/issues/66#issuecomment-151837230
> .

## 

Lucas Lima
Brasa Design e Tecnologia - Veja  http://web.brasa.art.br/Nosso Portifólio
http://web.brasa.art.br/
brasa.art.br | aoseudispor@brasa.art.br | Tel.: (11)  3042-4475

**Comment by LuwkasLima** [comment]
@matheusgimenez vc sabe me dizer porque as taxonomias nao estao aparecendo no filtro?

![image](https://cloud.githubusercontent.com/assets/5949986/10825342/9dfb7f36-7e32-11e5-90fd-3fbd84431712.png)

Eu ja configurei elas no Dashboard:

![image](https://cloud.githubusercontent.com/assets/5949986/10825478/306fc750-7e33-11e5-9bde-035ede8a0905.png)

**Comment by matheusgimenez** [comment]
Tem produtos marcados com elas?

**Comment by LuwkasLima** [comment]
Opa, claro mano!...hehehhe

**Comment by LuwkasLima** [comment]
@everaldomatias e @matheusgimenez fiz um teste aqui e removi um dos que estavam antes "Product Condition" e ele saiu. Dai coloquei de novo e agora nao aparece mais. Sera que eh algo do CSS?

![image](https://cloud.githubusercontent.com/assets/5949986/10851178/9af3a488-7ef7-11e5-8b09-47333824f34e.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez voce chegou a comitar a mudanca?

**Comment by matheusgimenez** [comment]
@LuwkasLima https://github.com/brasadesign/wp-docklands/commit/4e0f0367fd666f6e2c4c7f705e83fbbe97464d57
