### ISSUE TITLE
[Prioridade Baixa] Pente Fino - Ajustar Imagens (Thumbnails) dos produtos

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#70]
Oi Pessoal,

Precisamos buscar uma solucao pra arrumar os Thumbnails dos produtos, pois o corte ficou como um "ZOOM" e nao ta legal.

![image](https://cloud.githubusercontent.com/assets/5949986/10815029/7e54123c-7df7-11e5-9224-c7b5cb70f3ea.png)

Preciso saber tbm se eh melhor fazer isso em ambiente de Producao?

At.

**Comment by LuwkasLima** [comment]
@everaldomatias como fazemos nesse aqui? Usamos o plugin? Bora fazer um teste no brasawp?

**Comment by matheusgimenez** [comment]
Essa issue ta pra mim nas ações da esteira porem aqui no git, nao.

Enfim, de qlq forma deixarei umas duvidas aqui:

Precisamos criar um novo size? Se mudarmos o size do WooCommerce já não rola?

Já foi decidido qual é o tamanho? 400x400px?
@LuwkasLima @everaldomatias

**Comment by LuwkasLima** [comment]
@matheusgimenez entao, eu ja ajustei isso o Woo e parece que para os produtos novos esta OK. O problema sao os que subimos anteriormente, como a configuracao estava errada, ferrou tudo e eu nao sei como fariamos pra arrumar?

O @everaldomatias comentou de um plugin que recria os Thumbnails, voce conhece?

**Comment by matheusgimenez** [comment]
@LuwkasLima Vou rodar em produção, ok? É um plugin chamado Regenerate Thumbnails

**Comment by LuwkasLima** [comment]
@matheusgimenez eu estou trabalhando com o script pra regenerar os thumbnails, mas acabei descobrindo um outro probleminha que preciso da sua ajuda. Veja abaixo:

Existem situacoes onde a BORDA da fotos na parte de baixo nao aparece:

![image](https://cloud.githubusercontent.com/assets/5949986/19190745/dcf15c06-8c64-11e6-9c19-e4e61b2c888c.png)

Eu fiz um experimento e percebi que isso se da porque o box debaixo esta encobrindo a borda por causa do "padding" que esta marcado para 15px. Se eu mudo pra 10px fica certinho:

![image](https://cloud.githubusercontent.com/assets/5949986/19190827/38ad3dc6-8c65-11e6-912d-ba88d70835cd.png)

Nao sei se essa eh a solucao definitiva, por isso queria a sua analize.

**Comment by LuwkasLima** [comment]
Aprovado! - Pode enviar pra producao...

**Comment by LuwkasLima** [comment]
Em Produção!
