### ISSUE TITLE
Sem Paginacao em "Advanced Search"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#72]
@matheusgimenez voce pode por gentilza verificar porque a pagina "Advanced Search" esta sem paginacao?

![image](https://cloud.githubusercontent.com/assets/5949986/11000942/256f20fc-846a-11e5-88f9-15a266053361.png)

**Comment by matheusgimenez** [comment]
feito

**Comment by matheusgimenez** [comment]
resolvi com condicional.. testa e diz se agora ta ok! :)

**Comment by LuwkasLima** [comment]
Lindo!

**Comment by LuwkasLima** [comment]
@matheusgimenez passou um bug pelos nossos testes (vou precisar tomar mais cuidado).

Quando escolhemos para apresentar mais de 12 produtos na Paginacao, ele aplica isso para a lista de Produtos, mas tambem para a lista do widget SPECIALS e para a lista de "Recent Viewed":

![image](https://cloud.githubusercontent.com/assets/5949986/16098087/029162d2-3317-11e6-8e40-addc72efe85f.png)

Isso acontece em Producao e em Desenvolvimento:

http://www.docklandsfurniture.com/advanced-search/?per_page=24
http://brasawp.art.br/docklands/shop/?per_page=24

**Comment by LuwkasLima** [comment]
@matheusgimenez encontrei outro bug. =(

Agora, quando escolhemos 24 ou 36 produtos por pagina, ele aplica a logica no Widget SPECIALS:

1 - 12 por Pagina:

![image](https://cloud.githubusercontent.com/assets/5949986/20975677/d5acd30e-bc65-11e6-8ed8-afc65de0c745.png)

2 - 24 por pagina:

![image](https://cloud.githubusercontent.com/assets/5949986/20975718/f172f1a4-bc65-11e6-99cd-d39c266aae35.png)

![image](https://cloud.githubusercontent.com/assets/5949986/20975741/fcc3ffee-bc65-11e6-9600-3193af14f480.png)

**Comment by LuwkasLima** [comment]
Esta OK! Podemos mover pra Producao.
