### ISSUE TITLE
Produto Aparece como "Out of stock" mas possui estoque

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#75]
@matheusgimenez estou com um caso curioso aqui. O produto abaixo aparece como "Out of stock":

link: http://brasawp.art.br/docklands/product/single-desk-adapt-ii/

![image](https://cloud.githubusercontent.com/assets/5949986/11132066/74be6d28-8953-11e5-8984-0e535925bd4d.png)

No entanto, se verificamos o Produto e todas as suas variações, todos possuem estoque e status "In Stock":

![image](https://cloud.githubusercontent.com/assets/5949986/11132077/92ad7e96-8953-11e5-95d8-d6c91e4af8ae.png)

Variações:

![image](https://cloud.githubusercontent.com/assets/5949986/11132087/a2aaa260-8953-11e5-964b-5628cbc3043d.png)

**Comment by matheusgimenez** [comment]
fixado
