### ISSUE TITLE
[URGENTE] "Notice" quando clico em "Add to Enquire" sem selecionar uma opção de Produto

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#77]
Quando clicamos em "Add to Enquire" sem selecionar uma variação de produto, a seguinte mensagegm aparece no topo do site:

![image](https://cloud.githubusercontent.com/assets/5949986/11158659/4ff990d6-8a1f-11e5-8b47-a50266691ed4.png)

para reproduzir, apenas descelecione as opções do menu dropdown e clique em "add to enquire":

![image](https://cloud.githubusercontent.com/assets/5949986/11158679/6c0099f0-8a1f-11e5-8fb6-340be86d44ff.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez marquei como urgente pois como esta em producao agora, pode afetar a perspectiva do cliente quanto a qualidade da entrega.

**Comment by matheusgimenez** [comment]
Isso é porque temos que ter um JS antes de enviar o form. Amanhã faço um JS dando um aviso pedindo pra preencher.

**Comment by LuwkasLima** [comment]
Perfeito a solucao! Obrigado...
