### ISSUE TITLE
Categoria e Título da Página não "batem"

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#78]
Estou verificando uma "Table" dentro da categoria "Table", mas o título principal da página aparece "Storage":

![image](https://cloud.githubusercontent.com/assets/5949986/11159715/c8f8931c-8a27-11e5-8e77-722570a6f3c4.png)

**Comment by matheusgimenez** [comment]
@LuwkasLima isso ta em html puro.. não sei pra que serve

**Comment by LuwkasLima** [comment]
@everaldomatias verifica o que fazer com isso nesse caso. Se tiver duvidas me avise...
