### ISSUE TITLE
Area de Twitter sem formatacao

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#80]
@everaldomatias a area do Twitter esta sem formatacao. Precisamos definir uma formatacao para o Plugin. Como esta no Layout?
![image](https://cloud.githubusercontent.com/assets/5949986/11227264/9e739990-8d4a-11e5-9843-ae4573dcab00.png)

**Comment by everaldomatias** [comment]
![print-dock-2](https://cloud.githubusercontent.com/assets/1918474/11392664/53e53f8e-9342-11e5-99ef-feae93f25bcb.jpg)

Mas esse é o layout, está de acordo. O que precisa é colocar a conta da Docklands e não a do Matheus. Assim os tweets serão maiores @LuwkasLima.
