### ISSUE TITLE
Problema navegação do Matching Products

### ISSUE THREAD

**Issue by diogosp** [brasadesign/wp-docklands#83]
Percebi que é preciso ajustar melhor a janela de navegação do Matching Products. As setas de navegação estão cobrindo parte do conteúdo dos posts nos cantos.

<img width="1004" alt="captura de tela 2015-11-18 as 19 07 08" src="https://cloud.githubusercontent.com/assets/5107285/11254523/562a1752-8e28-11e5-8d89-8e372e25b7e4.png">

exemplo que peguei:
http://brasawp.art.br/docklands/product/bombo-gloss-bar-stool/

Mas deve ter outros.

**Comment by LuwkasLima** [comment]
@everaldomatias preciso que arrume isso no CSS durante o Pente Fino. Obrigado!

**Comment by everaldomatias** [comment]
@matheusgimenez pode me ajudar colocando um slider nisso aqui?
Eu finalizo o CSS.
Obrigado..

**Comment by everaldomatias** [comment]
@matheusgimenez vc fechou aqui com o slider?

**Comment by matheusgimenez** [comment]
Sim

-----Mensagem Original-----
De: "Everaldo Matias" notifications@github.com
Enviada em: ‎24/‎11/‎2015 22:58
Para: "brasadesign/wp-docklands" wp-docklands@noreply.github.com
Cc: "Matheus Gimenez Petroni" contato@matheusgimenez.com.br
Assunto: Re: [wp-docklands] Problema navegação do Matching Products (#83)

@matheusgimenez vc fechou aqui com o slider?

---

**Comment by LuwkasLima** [comment]
ta rolando um "pauzinho" no slider (naveguem pra vc ver)

![image](https://cloud.githubusercontent.com/assets/5949986/11425833/80f2432e-941d-11e5-971b-23b24243fadb.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez lembro de voce dar uma olhada nisso, mas ainda ta rolando. Chegou a fazer algo adicional?

**Comment by LuwkasLima** [comment]
Fechado ate que provem o contrario..
