### ISSUE TITLE
[URGENTE] UK Post Code - Probleminha com a logica

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#85]
@matheusgimenez precisamos urgentemente (digo urgente porque o site ja esta no ar e isso vai impactar as vendas) resolver um problema com a logica de calculo do shipping. Vou explicar detalhes:

A planilha enviada pela cliente possui diversas situacoes de calculo de shipping. Um deles é a definição do valor do shipping com base e uma região de 2 digitos:

![image](https://cloud.githubusercontent.com/assets/5949986/11285630/27741ada-8ed6-11e5-9a5b-51ef6af934bf.png)

Hoje a logica é de 2 digitos seguidos de espaço e "estrela" para capturar qualquer codigo que venha depois (pois não interessa segundo a planilha):

![image](https://cloud.githubusercontent.com/assets/5949986/11285727/b11a890e-8ed6-11e5-9a9c-058133949f51.png)

No entanto, no caso de codigos de 2 digitos como esses, as possibilidades de post code possuem um digito a mais SEM ESPAÇO:

![image](https://cloud.githubusercontent.com/assets/5949986/11286410/656a5b70-8eda-11e5-89ac-ccff5ef91d7d.png)

Mesmo se eu removo o espaço e coloco a "estrela" logo depois do "BR" não funciona =(

![image](https://cloud.githubusercontent.com/assets/5949986/11286448/967bed82-8eda-11e5-83e0-2f81d529399e.png)
![image](https://cloud.githubusercontent.com/assets/5949986/11286459/a29f1de6-8eda-11e5-934a-1c05fdf6fb03.png)

**Comment by LuwkasLima** [comment]
Tentei meter na mão, mas 4 digitos não é aceito:

![image](https://cloud.githubusercontent.com/assets/5949986/11306183/fe16ae1e-8f75-11e5-8ae3-4e1b808274de.png)

O BR98 não funciona...

![image](https://cloud.githubusercontent.com/assets/5949986/11306192/0f56830c-8f76-11e5-9d5e-050a4629e90d.png)

**Comment by LuwkasLima** [comment]
@matheusgimenez vou tentar explicar como funciona os Post Codes de UK e a lógica da Planilha da Docklands:

Nesse site você consegue ver todos as "Post Codes Areas" (o nivel mais alto de Post Codes): http://www.doogal.co.uk/UKPostcodes.php

![image](https://cloud.githubusercontent.com/assets/5949986/11310969/78a42a50-8f92-11e5-8db7-62591966a376.png)

Estas são as áreas maiores. Cada uma delas é quebrada em áreas menores (Districts) e depois em menores ainda que são os Post Codes utilizados pelos clientes e para calculo do Shipping:

Area > Distrito > Localização do Cliente

http://www.doogal.co.uk/UKPostcodes.php?Search=BR

Exemplo: BR1 1AA

O valor do shipping será dado de acordo com a planilha enviada pela Cliente. algumas vezes este valor é aplicado a uma AREA (ex.: BR, CR, DA) e neste caso, independente do post code colocado, o mesmo valor será aplicado.

![image](https://cloud.githubusercontent.com/assets/5949986/11311097/58d32112-8f93-11e5-9e21-d5d9ce73acea.png)

Ex.: Se eu moro em "BR1 1AA" o valor cobrado será de $60. Se eu morar em BR2 0AP será também $60.

No entanto, podem haver casos de aplicação de valor em niveis menores, como em Distritos (ex: SE1, SW3, W8, etc..). 

Por esse motivo, e importante que a lógica primeiro busque no array pelo nivel mais baixo e depois va quebrando o string (Post Code do Cliente) e verificando até encontrar o valor correspondente.

Exemplo:

Vamos dizer que temos no array de shipping os seguintes valores (Post Code;Preço):

Array -> [EC3A;$50, WC1E;$100,WC;$80]

Dai temos o seguinte cenário:

Post Code do Cliente -> WC1E 6AP (string)

Primeira iteração:

String = "WC1E 6AP"
Busca por "WC1E 6AP" no Array de Shipping [EC3A;$50, WC1E;$100,WC;$80]
Se não encontrar, quebra a string no último elemento
String = "WC1E 6A"

Segunda Iteração:

String = "WC1E 6A"
Busca por "WC1E 6A" no Array de Shipping [EC3A;$50, WC1E;$100,WC;$80]
Se não encontrar, quebra a string no último elemento
String = "WC1E 6"

...

Quinta Iteração:

String = "WC1E"
Busca por "WC1E" no Array de Shipping [EC3A;$50, WC1E;$100,WC;$80]
Encontra a string e retorna $100

Exemplo 2:

Array -> [EC3A;$50, WC1E;$100,WC;$80]
Post Code do Cliente -> WC2E 6AP

Primeira iteração:

String = "WC2E 6AP"
Busca por "WC2E 6AP" no Array de Shipping [EC3A;$50, WC1E;$100,WC;$80]
Se não encontrar, quebra a string no último elemento
String = "WC2E 6A"

Segunda, Terceira, Quarta...

Sexta Iteração:

String = "WC"
Busca por "WC" no Array de Shipping [EC3A;$50, WC1E;$100,WC;$80]
Retorna $80

**Comment by LuwkasLima** [comment]
@matheusgimenez eu vi que vc deu push na atualizacao do Plugin. Chegou a subir em producao?

**Comment by matheusgimenez** [comment]
@LuwkasLima Acho que subi.. mas não tenho certeza

**Comment by LuwkasLima** [comment]
@matheusgimenez legal mano! Ta supimpa, obrigado!!!...

Fechando...
