### ISSUE TITLE
Widget > Twitter

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/wp-docklands#9]
@matheusgimenez temos a demanda de colocar o twitter na Home, como está no layout. Mas se não for muito complexo, gostaria de não usar plugin apenas para isso, será que podemos fazer um Widget nosso para isso.

Se sim, já pense ele bem 'modular' para usarmos em outros projetos.

![print-twitter](https://cloud.githubusercontent.com/assets/1918474/5852743/e55366e4-a202-11e4-9d2e-41300f98293f.jpg)

**Comment by matheusgimenez** [comment]
Vou fazer via JS, assim carrega só depois do load.. não vai ficar pesado pro servidor enviar requisição HTTP

**Comment by matheusgimenez** [comment]
Mas já vi que vai ser um saco usar essa API do twitter
