### ISSUE TITLE
[IMPORTANTE] Desativar Plugins que nao sao utilizados

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#90]
@everaldomatias e @matheusgimenez me ajudem a entender quais Plugin sao desnecessarios e que podemos remover do ambiente de producao (Nao removam o de importacao de produtos ainda)!

@everaldomatias precisamos incluir o do CHAT

**Comment by everaldomatias** [comment]
Os que entendi que são necessários, pelo BrasaWP são:

• Alo EasyMail Newsletter
• Brasa Slider
• Contact Form 7
• JetPack (Não ví onde está sendo usado)
• PayPal for WooCommerce
• WooCommerce
• WooCommerce UK Postcodes Shipping
• WOOF - WooCommerce Products Filter
• Yoast SEO

Já o do chat, qual será? Aquele TidioChat que usávamos na Brasa não tem mais versão free. O teste deles é bem curto, tipo uma semana e já cai no premium. Temos que avaliar outro ou sugerir a compra? Esse Tidio custa US$ 10 por usuário.

**Comment by LuwkasLima** [comment]
@everaldomathias acho que a lista ta correta sim, mas quem sabe identifixar melhor é vocês mesmo. Tem que ver se o Cron do Matheus não tem um plugin tbm...

Sobre.o Chat, temos que achar uma solução, porque ela pediu pra intalarmos ele. Se o Tidio funcionou bem e é Pago, posso propor a instalação e eles contratam o serviço.

**Comment by LuwkasLima** [comment]
@matheusgimenez da seu OK aqui pra limparmos a lista de plugins...

**Comment by matheusgimenez** [comment]
O cron ta no tema.

O jetpack ta sendo usado no compartilhar do blog.

**Comment by LuwkasLima** [comment]
Completo!
