### ISSUE TITLE
[URGENTE] Problema com "Dynamic Recount" no Filtro

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/wp-docklands#91]
@matheusgimenez como explicado por Telegram, infelizmente nao amos poder deixar isso desligado. Vamos precisar encontrar a solucao para o problema de performance quando esta marcada a opcao de "Dynamic Recount" no filtro do site:

![image](https://cloud.githubusercontent.com/assets/5949986/11288257/0f7f6364-8ee8-11e5-871b-f6604c88455a.png)

![image](https://cloud.githubusercontent.com/assets/5949986/11288254/ff8d59de-8ee7-11e5-8a90-775fe60b20bd.png)

Se voce perceber que eh limitacao do server, consigo avisar a cliente para que comprem uma opcao melhor. Mas eu acho que eh outra coisa, pois nao chega nem a mostrar os produtos mesmo depois de 1h...

**Comment by matheusgimenez** [comment]
@LuwkasLima sobre isso, eu tava pensando.. será q pode ser algo q deixei pra trás na migraçao? seria interessante resetarmos esse plugin

**Comment by LuwkasLima** [comment]
@matheusgimenez eu pensei nisso tbm, ia propor fazer um upload dos arquivos de novo, ou resetar que nem vc falou. Nao tem problema nenhum, mas vou tentar coordenar com a cliente antes pra nao atrapalhar a apresentacao deles oK?

Me avisa quando voce estiver disponivel pra fazermos isso e eu converso com ela.

**Comment by LuwkasLima** [comment]
Descobri!

O Plugin possui um Cache que precisa ser limpo com frequencia. Eu limpei o Cache e voltou a funcionar...

![image](https://cloud.githubusercontent.com/assets/5949986/11341329/ac84ff52-91c7-11e5-9ea3-b6a7e88d0c76.png)

Coloquei pra ele limpar a cada hora pra não dar problema!
